firmware: dmi-id: add a release callback function
Mainline: cf770af5645a41a753c55a053fa1237105b0964a
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit cf770af5645a41a753c55a053fa1237105b0964a ]

dmi_class uses kfree() as the .release function, but that now causes
a warning with clang-16 as it violates control flow integrity (KCFI)
rules:

drivers/firmware/dmi-id.c:174:17: error: cast from 'void (*)(const void *)' to 'void (*)(struct device *)' converts to incompatible function type [-Werror,-Wcast-function-type-strict]
  174 |         .dev_release = (void(*)(struct device *)) kfree,

Add an explicit function to call kfree() instead.

Fixes: 4f5c791a850e ("DMI-based module autoloading")
Link: https://lore.kernel.org/lkml/20240213100238.456912-1-arnd@kernel.org/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jean Delvare <jdelvare@suse.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 1f428149492fbbba125378227effacba3b15c5a1)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I2f85b2d1ac872e45da81a0e6bf103f8e555ec165
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118316
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>