LoongArch: signal.c: add header file to fix build error
Mainline: c968b99f868dd82ebcafec9788ce18334da177b6
From: v6.8-rc1
Severity: Moderate

task: 217982

loongarch's signal.c uses rseq_signal_deliver() so it should
pull in the appropriate header to prevent a build error:

../arch/loongarch/kernel/signal.c: In function 'handle_signal':
../arch/loongarch/kernel/signal.c:1034:9: error: implicit declaration of function 'rseq_signal_deliver' [-Werror=implicit-function-declaration]
 1034 |         rseq_signal_deliver(ksig, regs);
      |         ^~~~~~~~~~~~~~~~~~~

Fixes: b74baf4ad05b ("LoongArch: Add signal handling support")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Huacai Chen <chenhuacai@kernel.org>
Cc: WANG Xuerui <kernel@xen0n.name>
Cc: loongarch@lists.linux.dev
Cc: Kent Overstreet <kent.overstreet@linux.dev>
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>

(backported from commit c968b99f868dd82ebcafec9788ce18334da177b6)

K2CI-Arch: Loongarch
Signed-off-by: George Guo <guodongtai@kylinos.cn>
Change-Id: Ie480d42968ae265eef01c4039a5de0e43ac37760
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/110823
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Reviewed-by: cuitao <cuitao@kylinos.cn>