qed: avoid truncating work queue length
Mainline: 954fd908f177604d4cce77e2a88cc50b29bad5ff
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 954fd908f177604d4cce77e2a88cc50b29bad5ff ]

clang complains that the temporary string for the name passed into
alloc_workqueue() is too short for its contents:

drivers/net/ethernet/qlogic/qed/qed_main.c:1218:3: error: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 18 [-Werror,-Wformat-truncation]

There is no need for a temporary buffer, and the actual name of a workqueue
is 32 bytes (WQ_NAME_LEN), so just use the interface as intended to avoid
the truncation.

Fixes: 59ccf86fe69a ("qed: Add driver infrastucture for handling mfw requests.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240326223825.4084412-4-arnd@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 6541f8ea7623a5c87b59905c4bccba175b68de2d)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I400e61e9ca7aa9cd5c613617ff9a09b36a7de19d
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118062
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>