drm/exynos: fix a potential error pointer dereference
Mainline: 73bf1c9ae6c054c53b8e84452c5e46f86dd28246
From: v6.7-rc5
Severity: Moderate

task: 196396

[ Upstream commit 73bf1c9ae6c054c53b8e84452c5e46f86dd28246 ]

Smatch reports the warning below:
drivers/gpu/drm/exynos/exynos_hdmi.c:1864 hdmi_bind()
error: 'crtc' dereferencing possible ERR_PTR()

The return value of exynos_drm_crtc_get_by_type maybe ERR_PTR(-ENODEV),
which can not be used directly. Fix this by checking the return value
before using it.

Signed-off-by: Xiang Yang <xiangyang3@huawei.com>
Signed-off-by: Inki Dae <inki.dae@samsung.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 2debe511c1d28dfc73e2e352de70fdec9a503833)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I11dc438109851acb8ebf87d5995d37a8bd43ebc3
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/93338
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>