nvme-pci: disable secondary temp for Wodposit WPBSNM8
Mainline: 340f4fc5508c2905a1f30de229e2a4b299d55735
From: v6.19-rc6
Severity: Moderate

task: 594541

commit 340f4fc5508c2905a1f30de229e2a4b299d55735 upstream.

Secondary temperature thresholds (temp2_{min,max}) were not reported
properly on this NVMe SSD. This resulted in an error while attempting to
read these values with sensors(1):

  ERROR: Can't get value of subfeature temp2_min: I/O error
  ERROR: Can't get value of subfeature temp2_max: I/O error

Add the device to the nvme_id_table with the
NVME_QUIRK_NO_SECONDARY_TEMP_THRESH flag to suppress access to all non-
composite temperature thresholds.

Cc: stable@vger.kernel.org
Tested-by: Wu Haotian <rigoligo03@gmail.com>
Signed-off-by: Ilikara Zheng <ilikara@aosc.io>
Signed-off-by: Keith Busch <kbusch@kernel.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit ed61badfc2bc859250886b3e3e3b12ab75017973)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I62a06f459e496639ad8e4268892b7398d9a9c786
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/174501
Reviewed-by: 刘云 <liuyun01@kylinos.cn>