LoongArch: Fix a build error due to __tlb_remove_tlb_entry()
Mainline: 7ab22b5c2af54e233f3d05d7d601025947e4ff05
From: v6.9-rc6
Severity: Moderate

task: 217982

With LLVM=1 and W=1 we get:

  ./include/asm-generic/tlb.h:629:10: error: parameter 'ptep' set
  but not used [-Werror,-Wunused-but-set-parameter]

We fixed a similar issue via Arnd in the introducing commit, missed the
LoongArch variant. Turns out, there is no need for LoongArch to have a
custom variant, so let's just drop it and rely on the asm-generic one.

Fixes: 4d5bf0b6183f ("mm/mmu_gather: add tlb_remove_tlb_entries()")
Closes: https://lkml.kernel.org/r/CANiq72mQh3O9S4umbvrKBgMMorty48UMwS01U22FR0mRyd3cyQ@mail.gmail.com
Reported-by: Miguel Ojeda <ojeda@kernel.org>
Reviewed-by: Miguel Ojeda <ojeda@kernel.org>
Tested-by: Miguel Ojeda <ojeda@kernel.org>
Tested-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David Hildenbrand <david@redhat.com>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>

(backported from commit 7ab22b5c2af54e233f3d05d7d601025947e4ff05)

K2CI-Arch: Loongarch
Signed-off-by: George Guo <guodongtai@kylinos.cn>
Change-Id: I2531a7d13230763c80f1f6d22acf6399cdee3fd3
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/110860
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>