KYLIN: efi: comment an unused function when not x86 arch
Mainline: KYLIN-only
Severity: Important

task: 221001

When compile kernel with allyesconfig, the following error occurred:

drivers/firmware/efi/cper.c:173:13: error: ‘cper_print_proc_generic_zdi_zpi’
defined but not used [-Werror=unused-function]
  173 | static void cper_print_proc_generic_zdi_zpi(const char *pfx,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

This function can only be called in x86 arch, so comment this function in
other archs to fix it.

K2CI-Arch: All
Signed-off-by: chizhiling <chizhiling@kylinos.cn>
Reported-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Id1436b522e40371338c67f5bc2f5e8d81c759231
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/113815
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>