md: factor out a helper to choose sync action from md_check_recovery()
Mainline: 897c62a1cae6485870a45934b22c180016a0570f
From: v6.7-rc1
Severity: Moderate

task: 211761

There are no functional changes, on the one hand make the code cleaner,
on the other hand prevent following checkpatch error in the next patch to
delay choosing sync action to md_start_sync().

ERROR: do not use assignment in if condition
+       } else if ((spares = remove_and_add_spares(mddev, NULL))) {

Signed-off-by: Yu Kuai <yukuai3@huawei.com>
Reviewed-by: Xiao Ni <xni@redhat.com>
Signed-off-by: Song Liu <song@kernel.org>
Link: https://lore.kernel.org/r/20230825031622.1530464-3-yukuai1@huaweicloud.com
(backported from commit 897c62a1cae6485870a45934b22c180016a0570f)

K2CI-Arch: All
Signed-off-by: lifangxu <lifangxu@kylinos.cn>
Change-Id: I2be55aa2228bd720cde7f91a890255c42b96658c
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/106869
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>