dm integrity: fix out-of-range warning
Mainline: 8e91c2342351e0f5ef6c0a704384a7f6fc70c3b2
From: v6.9-rc2
Severity: Moderate

task: 211027

[ Upstream commit 8e91c2342351e0f5ef6c0a704384a7f6fc70c3b2 ]

Depending on the value of CONFIG_HZ, clang complains about a pointless
comparison:

drivers/md/dm-integrity.c:4085:12: error: result of comparison of
                        constant 42949672950 with expression of type
                        'unsigned int' is always false
                        [-Werror,-Wtautological-constant-out-of-range-compare]
                        if (val >= (uint64_t)UINT_MAX * 1000 / HZ) {

As the check remains useful for other configurations, shut up the
warning by adding a second type cast to uint64_t.

Fixes: 468dfca38b1a ("dm integrity: add a bitmap mode")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Mikulas Patocka <mpatocka@redhat.com>
Reviewed-by: Justin Stitt <justinstitt@google.com>
Signed-off-by: Mike Snitzer <snitzer@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 7cd73d90856d7edec080b356a33959b57a241598)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I1cc9adf6ad25a3272000cbf1a75c94f286c972e1
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/105907
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>