tools/virtio: Add DMA_MAPPING_ERROR and sg_dma_len api define for virtio test
Mainline: ae376910f52b815003d433243bee93ca000537c0
From: v6.15-rc1
Severity: Low

task: #451679

when we build tools/virtio, meet below error information.

cc -g -O2 -Werror -Wno-maybe-uninitialized -Wall -I. -I../include/
-I ../../usr/include/ -Wno-pointer-sign -fno-strict-overflow
-fno-strict-aliasing -fno-common -MMD
-U_FORTIFY_SOURCE -include ../../include/linux/kconfig.h
-mfunction-return=thunk
-fcf-protection=none -mindirect-branch-register -pthread
-c -o virtio_ring.o ../../drivers/virtio/virtio_ring.c

../../drivers/virtio/virtio_ring.c: in function 'vring_need_unmap_buffer':
../../drivers/virtio/virtio_ring.c:294:54: error:'DMA_MAPPING_ERROR'Undeclared (first use within this function)
  294 |         return vring->use_dma_api && (extra->addr != DMA_MAPPING_ERROR);
      |                                                      ^~~~~~~~~~~~~~~~~
../../drivers/virtio/virtio_ring.c:294:54: Note: Each undeclared identifier is only reported once within the function it appears in
../../drivers/virtio/virtio_ring.c: in function 'vring_map_one_sg':
../../drivers/virtio/virtio_ring.c:369:24: error：Implicit declaration function'sg_dma_len' [-Wimplicit-function-declaration]
  369 |                 *len = sg_dma_len(sg);
      |                        ^~~~~~~~~~
../../drivers/virtio/virtio_ring.c: in function'virtqueue_add_desc_split':
../../drivers/virtio/virtio_ring.c:518:37: error:'DMA_MAPPING_ERROR'Undeclared (first use within this function)
  518 |         extra[i].addr = premapped ? DMA_MAPPING_ERROR : addr;
      |                                     ^~~~~~~~~~~~~~~~~
../../drivers/virtio/virtio_ring.c: in function'virtqueue_add_indirect_packed':
../../drivers/virtio/virtio_ring.c:1370:61: error: 'DMA_MAPPING_ERROR'Undeclared (first use within this function)
 1370 |                             extra[i].addr = premapped ? DMA_MAPPING_ERROR : addr;
      |                                                         ^~~~~~~~~~~~~~~~~

../../drivers/virtio/virtio_ring.c: in function'virtqueue_add_packed':
../../drivers/virtio/virtio_ring.c:1535:41: error:'DMA_MAPPING_ERROR'Undeclared (first use within this function)
 1535 |                                         DMA_MAPPING_ERROR : addr;
      |                                         ^~~~~~~~~~~~~~~~~

to fix, add DMA_MAPPING_ERROR define for virtio test.

Fixes: c7e1b422afac ("virtio_ring: perform premapped operations based on per-buffer")
Signed-off-by: Yufeng Wang <wangyufeng@kylinos.cn>
Message-Id: <20250113100300.174382-1-wangyufeng@kylinos.cn>
Signed-off-by: Michael S. Tsirkin <mst@redhat.com>

K2CI-Arch: All
Signed-off-by: xiongweimin <xiongweimin@kylinos.cn>
Change-Id: Ib8cb1781726642641e013d2ec14e2bf3fca073bf
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/74923
Reviewed-by: 李唯实 <liweishi@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>