arch: consolidate arch_irq_work_raise prototypes
Mainline: 64bac5ea17d527872121adddfee869c7a0618f8f
From: v6.8-rc1
Severity: Moderate

task: 198520

[ Upstream commit 64bac5ea17d527872121adddfee869c7a0618f8f ]

The prototype was hidden in an #ifdef on x86, which causes a warning:

kernel/irq_work.c:72:13: error: no previous prototype for 'arch_irq_work_raise' [-Werror=missing-prototypes]

Some architectures have a working prototype, while others don't.
Fix this by providing it in only one place that is always visible.

Reviewed-by: Alexander Gordeev <agordeev@linux.ibm.com>
Acked-by: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Palmer Dabbelt <palmer@rivosinc.com>
Acked-by: Guo Ren <guoren@kernel.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 64e7f102c301d97e83e7a733678f3b4ad39fddfc)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ib4ca6520b79a5ddf0f215636c02f20210fb97ea0
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/96530
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>