bpftool: Fix -Wuninitialized-const-pointer warnings with clang >= 21
Mainline: 5612ea8b554375d45c14cbb0f8ea93ec5d172891
From: v6.18-rc1
Severity: Moderate

task: 561765

[ Upstream commit 5612ea8b554375d45c14cbb0f8ea93ec5d172891 ]

This fixes the build with -Werror -Wall.

btf_dumper.c:71:31: error: variable 'finfo' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
   71 |         info.func_info = ptr_to_u64(&finfo);
      |                                      ^~~~~

prog.c:2294:31: error: variable 'func_info' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 2294 |         info.func_info = ptr_to_u64(&func_info);
      |

v2:
  - Initialize instead of using memset.

Signed-off-by: Tom Stellard <tstellar@redhat.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Acked-by: Quentin Monnet <qmo@kernel.org>
Link: https://lore.kernel.org/bpf/20250917183847.318163-1-tstellar@redhat.com
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 4b78d57b7dd375f38b4f0be79a00530ba4ff5a11)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I54d3b43cd4781ef63632475944efa42b21555ea0
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/147679
Reviewed-by: 刘云 <liuyun01@kylinos.cn>