efi/capsule-loader: fix incorrect allocation size
Mainline: fccfa646ef3628097d59f7d9c1a3e84d4b6bb45e
From: v6.8-rc7
Severity: Moderate

task: 201962

[ Upstream commit fccfa646ef3628097d59f7d9c1a3e84d4b6bb45e ]

gcc-14 notices that the allocation with sizeof(void) on 32-bit architectures
is not enough for a 64-bit phys_addr_t:

drivers/firmware/efi/capsule-loader.c: In function 'efi_capsule_open':
drivers/firmware/efi/capsule-loader.c:295:24: error: allocation of insufficient size '4' for type 'phys_addr_t' {aka 'long long unsigned int'} with size '8' [-Werror=alloc-size]
  295 |         cap_info->phys = kzalloc(sizeof(void *), GFP_KERNEL);
      |                        ^

Use the correct type instead here.

Fixes: f24c4d478013 ("efi/capsule-loader: Reinstate virtual capsule mapping")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 11aabd7487857b8e7d768fefb092f66dfde68492)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ie7f34b016f6f36412d2bc5ebbfe5a0917b756be1
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/99026
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>