cgroup: Fix compilation issue due to cgroup_mutex not being exported
Mainline: 87c259a7a359e73e6c52c68fcbec79988999b4e6
From: v6.15-rc4
Severity: Moderate

task: 476205

[ Upstream commit 87c259a7a359e73e6c52c68fcbec79988999b4e6 ]

When adding folio_memcg function call in the zram module for
Android16-6.12, the following error occurs during compilation:
ERROR: modpost: "cgroup_mutex" [../soc-repo/zram.ko] undefined!

This error is caused by the indirect call to lockdep_is_held(&cgroup_mutex)
within folio_memcg. The export setting for cgroup_mutex is controlled by
the CONFIG_PROVE_RCU macro. If CONFIG_LOCKDEP is enabled while
CONFIG_PROVE_RCU is not, this compilation error will occur.

To resolve this issue, add a parallel macro CONFIG_LOCKDEP control to
ensure cgroup_mutex is properly exported when needed.

Signed-off-by: gao xu <gaoxu2@honor.com>
Acked-by: Michal Koutný <mkoutny@suse.com>
Signed-off-by: Tejun Heo <tj@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 20fb292ab5d5d87746dbfa6d4127c50a51f93a42)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ida24a472a3f789a6cca2ab27ef79f09f7768aee8
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/72809
Reviewed-by: 刘云 <liuyun01@kylinos.cn>