KYLIN: SCSI/SSSRAID: Fix fortify memcpy check error with flexible array
Mainline: KYLIN-only
Severity: Low

Task: 402067

This patch resolves a fortify memcpy check error triggered by GCC 13+
during allyesconfig compilation by replacing the zero-length event_data[0]
with a proper flexible array event_data[] in sssraid_fwevt struct.
Avoid out-of-boundary writes in memcpy operations.

In function ‘fortify_memcpy_chk’,
    inlined from ‘sssraid_process_admin_cq.isra’ at ../drivers/scsi/sssraid/sssraid_fw.c:1574:3:
include/linux/fortify-string.h:573:25: error: call to ‘__write_overflow_field’ declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
  573 | __write_overflow_field(p_size_field, size);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

K2CI-Arch: All
Fixes: 4c829f1c8f91 ("3SNIC: SCSI/SSSRAID: Support 3SNIC 3S5XX serial RAID/HBA controllers")
Signed-off-by: lifangxu <lifangxu@kylinos.cn>
Change-Id: I050182551bffd4a6dc3a451a11eecb141f75b895
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/153119
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>