sh: hd64461: Make setup_hd64461() static
Mainline: 1e21acb7fbfb15fcb4afe21fb5a50a1bc00743ec
From: v6.9-rc1
Severity: Moderate

task: 225985

Enforce internal linkage for setup_hd64461().

This fixes the following error:
arch/sh/cchips/hd6446x/hd64461.c:75:12: error: no previous prototype for 'setup_hd64461' [-Werror=missing-prototypes]

Signed-off-by: Artur Rojek <contact@artur-rojek.eu>
Reviewed-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
Link: https://lore.kernel.org/r/20240211193451.106795-1-contact@artur-rojek.eu
Signed-off-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>

(backported from commit 1e21acb7fbfb15fcb4afe21fb5a50a1bc00743ec)

K2CI-Arch: All
Signed-off-by: jindongyang <jindongyang@kylinos.cn>
Change-Id: Iedbc6c55cb77dd67b7a02d31dd2135707521ee6b
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/117648
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>