selftests/powerpc: Fix load_unaligned_zeropad build failure
Mainline: 3fe1eb4dd2e4b872ffb7b9b081b34ffcfa934ba7
From: v6.9-rc1
Severity: Low

This test is userspace code, but uses some kernel headers via symlinks,
and mocks other headers, in order to test load_unaligned_zeropad().

Currently the test fails to build with:

  In file included from load_unaligned_zeropad.c:26:
  word-at-a-time.h:7:10: fatal error: linux/bitops.h: No such file or directory
      7 | #include <linux/bitops.h>

This is due to the recent changes to the kernel headers.

Fix it by symlinking the new wordpart.h, and creating an empty stub for
bitops.h which is all that's needed.

Reported-by: Sachin Sant <sachinp@linux.ibm.com>
Tested-by: Sachin Sant <sachinp@linux.ibm.com>
Fixes: 66a5c40f60f5 ("kernel.h: removed REPEAT_BYTE from kernel.h")
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20240305125644.3315910-1-mpe@ellerman.id.au
Signed-off-by: Kees Cook <keescook@chromium.org>

(backported from commit 3fe1eb4dd2e4b872ffb7b9b081b34ffcfa934ba7)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I68837a0319322eb6e1cd283c6df0c22b43be35a1
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/120136
Tested-by: kernel-bot <kernel-bot@kylinos.cn>