selftests/landlock: Fix net_test build with old libc
Mainline: 116099ed345c932a8ae4a0d884a8f6cc54fd5fed
From: v6.8-rc5
Severity: Moderate

task: 369031

One issue comes up while building selftest/landlock/net_test on my side
(gcc 7.3/glibc-2.28/kernel-4.19).

net_test.c: In function ‘set_service’:
net_test.c:91:45: warning: implicit declaration of function ‘gettid’; [-Wimplicit-function-declaration]
    "_selftests-landlock-net-tid%d-index%d", gettid(),
                                             ^~~~~~
                                             getgid
net_test.c:(.text+0x4e0): undefined reference to `gettid'

Signed-off-by: Hu Yadi <hu.yadi@h3c.com>
Suggested-by: Jiao <jiaoxupo@h3c.com>
Reviewed-by: Berlin <berlin@h3c.com>
Fixes: a549d055a22e ("selftests/landlock: Add network tests")
Link: https://lore.kernel.org/r/20240123062621.25082-1-hu.yadi@h3c.com
[mic: Cosmetic fixes]
Signed-off-by: Mickaël Salaün <mic@digikod.net>

(backported from commit 116099ed345c932a8ae4a0d884a8f6cc54fd5fed)

Signed-off-by: chenyuan <chenyuan@kylinos.cn>
Change-Id: If62bca3680f7f1f210eb88ab8ba5c09b1a51eb3b
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/139814
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>