KYLIN: tsm-mr: Fix __assign_str and bin_attriute compilation errors
Mainline: KYLIN-only
Severity: Important

Task: 511745

1. Adapt tracepoint __assign_str due to api has not changed.
2. Adapt sysfs bin_attriute callbacks due to api has not
   changed

Link: https://gitee.com/anolis/cloud-kernel/commit/196cced75ac0ddab5c04d1c369ac14eb8bb109fe
Fixes: a1da20f07c56 ("tsm-mr: Add TVM Measurement Register support")
Change-Id: I40bfb269c78c1adbe2aa43e51bcf52a7be643b1a
Signed-off-by: Haofeng Li <lihaofeng@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/110005
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>