KYLIN: cpufreq: fix compile error on i386_defconfig
Mainline: KYLIN-only
Severity: Low

Task: 417919

for compile error with i386_defconfig:
error: ‘sched_set_itmt’ defined but not used [-Werror=unused-function]
include sched_set_itmt under CONFIG_ACPI_CPPC_LIB define.

K2CI-Arch: All
Fixes: b4e9990b4f20 ("OPENEULER: cpufreq: ACPI: update new version for ITMT support")
Reported-by: k2ci <kernel-bot@kylinos.cn>
Signed-off-by: lifangxu <lifangxu@kylinos.cn>
Change-Id: I79ba15516bdb49dbf750dd57c39d1156be35fe84
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/152601
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>