hwmon: (tmp513) Add missing dependency on REGMAP_I2C
Mainline: 193bc02c664999581a1f38c152f379fce91afc0c
From: v6.12-rc3
Severity: Moderate

task: 373253

[ Upstream commit 193bc02c664999581a1f38c152f379fce91afc0c ]

0-day reports:

drivers/hwmon/tmp513.c:162:21: error:
	variable 'tmp51x_regmap_config' has initializer but incomplete type
162 | static const struct regmap_config tmp51x_regmap_config = {
    |                     ^

struct regmap_config is only available if REGMAP is enabled.
Add the missing Kconfig dependency to fix the problem.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202410020246.2cTDDx0X-lkp@intel.com/
Fixes: 59dfa75e5d82 ("hwmon: Add driver for Texas Instruments TMP512/513 sensor chips.")
Cc: Eric Tremblay <etremblay@distech-controls.com>
Reviewed-by: Javier Carrasco <javier.carrasco.cruz@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit de90999ec3de5d1788e65f07ae3ba4b5e41cfcd3)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I1a9efe1c9e43224dfd0317ce4cdf6d24cd504f43
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/139415
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>