ASoC: cs42l84: remove incorrect of_match_ptr()
Mainline: 0d4f74febc9d92d88099aff01f121b7f5f942c8f
From: v6.13-rc1
Severity: Moderate

task: 570975

The use of of_match_ptr() is incorrect here and just causes
a warning:

sound/soc/codecs/cs42l84.c:1084:34: error: unused variable 'cs42l84_of_match' [-Werror,-Wunused-const-variable]

Fixes: 250304a0fb34 ("ASoC: cs42l84: Add new codec driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20241029092404.3874040-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>

(backported from commit 0d4f74febc9d92d88099aff01f121b7f5f942c8f)

K2CI-Arch: All
Cc: kernel-stable-team #KLAD #2503+
Change-Id: Ie9381dca518aa4dc50bb9ae94cdfd03c605ac8de
Signed-off-by: lifangxu <lifangxu@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/157325
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>