gfs2: Set .migrate_folio in gfs2_{rgrp,meta}_aops
Mainline: 5c8f12cf1e64e0e8e6cb80b0c935389973e8be8d
From: v6.17-rc1
Severity: Moderate

task: 525135

[ Upstream commit 5c8f12cf1e64e0e8e6cb80b0c935389973e8be8d ]

Clears up the warning added in 7ee3647243e5 ("migrate: Remove call to
->writepage") that occurs in various xfstests, causing "something found
in dmesg" failures.

[  341.136573] gfs2_meta_aops does not implement migrate_folio
[  341.136953] WARNING: CPU: 1 PID: 36 at mm/migrate.c:944 move_to_new_folio+0x2f8/0x300

Signed-off-by: Andrew Price <anprice@redhat.com>
Signed-off-by: Andreas Gruenbacher <agruenba@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 3d2c05cbc6a3725d832b912b637971f37301c7e5)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ica04843fe6b156983d558dd4428696f1d304c165
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/108874
Reviewed-by: 刘云 <liuyun01@kylinos.cn>