fs/ntfs3: fix build without CONFIG_NTFS3_LZX_XPRESS
Mainline: c8e314624a1666ed2eec28549713021a8ec801e9
From: v6.8-rc7
Severity: Moderate

task: 201962

commit c8e314624a1666ed2eec28549713021a8ec801e9 upstream.

When CONFIG_NTFS3_LZX_XPRESS is not set then we get the following build
error:

  fs/ntfs3/frecord.c:2460:16: error: unused variable ‘i_size’

Signed-off-by: Mark O'Donovan <shiftee@posteo.net>
Fixes: 4fd6c08a16d7 ("fs/ntfs3: Use i_size_read and i_size_write")
Tested-by: Chris Clayton <chris2553@googlemail.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Reported-by: Rainer Fiebig <jrf@mailbox.org>
Cc: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit af0d04f02145f09564aa1ae8eacac07bfb570eb3)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ie1ee556ce9d8c125930365fbbd887dc6e74cf7fe
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/98984
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>