firmware: tegra: bpmp: Drop unused mbox_client_to_bpmp()
Mainline: 9c3a62c20f7fb00294a4237e287254456ba8a48b
From: v6.12-rc1
Severity: Moderate

task: 369107

commit 9c3a62c20f7fb00294a4237e287254456ba8a48b upstream.

mbox_client_to_bpmp() is not used, W=1 builds:

  drivers/firmware/tegra/bpmp.c:28:1: error: unused function 'mbox_client_to_bpmp' [-Werror,-Wunused-function]

Fixes: cdfa358b248e ("firmware: tegra: Refactor BPMP driver")
Cc: stable@vger.kernel.org
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Signed-off-by: Thierry Reding <treding@nvidia.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 028258156f657c50da6c84d36a346d34900253b5)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I47637b87e7c6257efc5d1cb40c44ab0827dc3e50
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/138078
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>