tools/net/ynl: ethtool: fix crash when Hardware Clock info is missing
Mainline: 45375814eb3f4245956c0c85092a4eee4441d167
From: v6.15-rc7
Severity: Moderate

task: 467324

[ Upstream commit 45375814eb3f4245956c0c85092a4eee4441d167 ]

Fix a crash in the ethtool YNL implementation when Hardware Clock information
is not present in the response. This ensures graceful handling of devices or
drivers that do not provide this optional field. e.g.

  Traceback (most recent call last):
    File "/net/tools/net/ynl/pyynl/./ethtool.py", line 438, in <module>
      main()
      ~~~~^^
    File "/net/tools/net/ynl/pyynl/./ethtool.py", line 341, in main
      print(f'PTP Hardware Clock: {tsinfo["phc-index"]}')
                                   ~~~~~~^^^^^^^^^^^^^
  KeyError: 'phc-index'

Fixes: f3d07b02b2b8 ("tools: ynl: ethtool testing tool")
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
Acked-by: Stanislav Fomichev <sdf@fomichev.me>
Link: https://patch.msgid.link/20250508035414.82974-1-liuhangbin@gmail.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 7777ca11a40bb9041db3e6f5800d89f855e5f482)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I15ecfdf1f30044766f9dcb14b7cb1dc8924bfeb1
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/67614
Reviewed-by: 刘云 <liuyun01@kylinos.cn>