scsi: qedf: Use designated initializer for struct qed_fcoe_cb_ops
Mainline: d8720235d5b5cad86c1f07f65117ef2a96f8bec7
From: v6.16-rc1
Severity: Moderate

task: 482699

[ Upstream commit d8720235d5b5cad86c1f07f65117ef2a96f8bec7 ]

Recent fixes to the randstruct GCC plugin allowed it to notice
that this structure is entirely function pointers and is therefore
subject to randomization, but doing so requires that it always use
designated initializers. Explicitly specify the "common" member as being
initialized. Silences:

drivers/scsi/qedf/qedf_main.c:702:9: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  702 |         {
      |         ^

Fixes: 035f7f87b729 ("randstruct: Enable Clang support")
Link: https://lore.kernel.org/r/20250502224156.work.617-kees@kernel.org
Signed-off-by: Kees Cook <kees@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit ee96502062ec0b91428bd1609d5eb18b90af64e5)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I46d33bad13ffa302f508240bb15c46a7ce79e62c
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/76947
Reviewed-by: 刘云 <liuyun01@kylinos.cn>