selftests/bpf: Fix missing ARRAY_SIZE() definition in bench.c
Mainline: d44c93fc2f5a0c47b23fa03d374e45259abd92d2
From: v6.12-rc1
Severity: Moderate

task: 366821

[ Upstream commit d44c93fc2f5a0c47b23fa03d374e45259abd92d2 ]

Add a "bpf_util.h" include to avoid the following error seen compiling for
mips64el with musl libc:

  bench.c: In function 'find_benchmark':
  bench.c:590:25: error: implicit declaration of function 'ARRAY_SIZE' [-Werror=implicit-function-declaration]
    590 |         for (i = 0; i < ARRAY_SIZE(benchs); i++) {
        |                         ^~~~~~~~~~
  cc1: all warnings being treated as errors

Fixes: 8e7c2a023ac0 ("selftests/bpf: Add benchmark runner infrastructure")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Link: https://lore.kernel.org/bpf/bc4dde77dfcd17a825d8f28f72f3292341966810.1721713597.git.tony.ambardar@gmail.com
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 2388d181667a728f1b91e17d4e9897ba739dcc43)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I2073721ac730d8b6192cf060698295ac38772c20
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/137269
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>