MIPS: BCM47XX: include header for bcm47xx_prom_highmem_init() prototype
Mainline: 34059321f4cf541d69e733cd02882d62c489bb77
From: v6.10-rc1
Severity: Moderate

task: #218078

bcm47xx_prom_highmem_init() is a global function declared in
arch/mips/bcm47xx/bcm47xx_private.h, but this header is not
included before the definition, causing a error:

arch/mips/bcm47xx/prom.c:134:13: error: no previous prototype \
	for ‘bcm47xx_prom_highmem_init’ [-Werror=missing-prototypes]
  134 | void __init bcm47xx_prom_highmem_init(void)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>
Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Signed-off-by: luoqing <luoqing@kylinos.cn>
Change-Id: Ib5c393d032b75475dba00d11a7265ae424590ffd
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/122283
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>