power: rt9455: hide unused rt9455_boost_voltage_values
Mainline: 452d8950db3e839aba1bb13bc5378f4bac11fa04
From: v6.9-rc7
Severity: Moderate

task: 220176

[ Upstream commit 452d8950db3e839aba1bb13bc5378f4bac11fa04 ]

The rt9455_boost_voltage_values[] array is only used when USB PHY
support is enabled, causing a W=1 warning otherwise:

drivers/power/supply/rt9455_charger.c:200:18: error: 'rt9455_boost_voltage_values' defined but not used [-Werror=unused-const-variable=]

Enclose the definition in the same #ifdef as the references to it.

Fixes: e86d69dd786e ("power_supply: Add support for Richtek RT9455 battery charger")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240403080702.3509288-10-arnd@kernel.org
Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 48e52633d519ea7421ede46338bc095e5d761a71)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Iecd783db5e3e8b8ac3a7237195d0d8bdb6cd29dc
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/112182
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>