ieee802154: Fix build error
Mainline: addf89774e48c992316449ffab4f29c2309ebefb
From: v6.12-rc2
Severity: Moderate

task: 369107

[ Upstream commit addf89774e48c992316449ffab4f29c2309ebefb ]

If REGMAP_SPI is m and IEEE802154_MCR20A is y,

	mcr20a.c:(.text+0x3ed6c5b): undefined reference to `__devm_regmap_init_spi'
	ld: mcr20a.c:(.text+0x3ed6cb5): undefined reference to `__devm_regmap_init_spi'

Select REGMAP_SPI for IEEE802154_MCR20A to fix it.

Fixes: 8c6ad9cc5157 ("ieee802154: Add NXP MCR20A IEEE 802.15.4 transceiver driver")
Signed-off-by: Jinjie Ruan <ruanjinjie@huawei.com>
Link: https://lore.kernel.org/20240909131740.1296608-1-ruanjinjie@huawei.com
Signed-off-by: Stefan Schmidt <stefan@datenfreihafen.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit d6c4c08670867cd4b01798528b7d335a0967b876)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I9f086e3047899f8f148c44e98fda0bda9753eb34
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/137886
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>