KYLIN: livepatch/test_module: Fix compilation errors on ARM
Mainline: KYLIN-only
Severity: Low

task: 425656

Fix compilation errors on ARM without CONFIG_LIVEPATCH_FTRACE.
On ARM architectures where CONFIG_LIVEPATCH_WO_FTRACE is enabled and
CONFIG_LIVEPATCH_FTRACE is disabled, compilation fails due to undefined
functions klp_enable_patch(), klp_get_state(), and klp_get_prev_state().
These functions are only available when CONFIG_LIVEPATCH_FTRACE is active.

Changes:
1. Replaced klp_enable_patch() with klp_register_patch() for ARM-
   specific configurations to maintain functionality without ftrace
   dependency.
2. Updated the Makefile to exclude problematic source files when
   CONFIG_LIVEPATCH_FTRACE is disabled, preventing references to
   undefined symbols.

K2CI-Arch: All
Signed-off-by: wudandan <wudandan@kylinos.cn>
Change-Id: I10f958005497d2aa2eaa3171236716d441a97040
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/96468
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>