parisc: fix building with gcc-15
Mainline: 7cbb015e2d3d6f180256cde0c908eab21268e7b9
From: v6.16-rc1
Severity: Moderate

task: 486465

commit 7cbb015e2d3d6f180256cde0c908eab21268e7b9 upstream.

The decompressor is built with the default C dialect, which is now gnu23
on gcc-15, and this clashes with the kernel's bool type definition:

In file included from include/uapi/linux/posix_types.h:5,
                 from arch/parisc/boot/compressed/misc.c:7:
include/linux/stddef.h:11:9: error: cannot use keyword 'false' as enumeration constant
   11 |         false   = 0,

Add the -std=gnu11 argument here, as we do for all other architectures.

Cc: stable@vger.kernel.org
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Helge Deller <deller@gmx.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit ebb8060561d552ab5acf23c65acec95f787929bf)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ia16e660205d3d8391431931c638d2b8e6637f027
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/79503
Reviewed-by: 刘云 <liuyun01@kylinos.cn>