iio: accel: fxls8962af: select IIO_BUFFER & IIO_KFIFO_BUF
Mainline: a821d7111e3f7c8869961b606714a299bfe20014
From: v6.10-rc6
Severity: Moderate

task: 332922

commit a821d7111e3f7c8869961b606714a299bfe20014 upstream.

Provide missing symbols to the module:
ERROR: modpost: iio_push_to_buffers [drivers/iio/accel/fxls8962af-core.ko] undefined!
ERROR: modpost: devm_iio_kfifo_buffer_setup_ext [drivers/iio/accel/fxls8962af-core.ko] undefined!

Cc: stable@vger.kernel.org
Fixes: 79e3a5bdd9ef ("iio: accel: fxls8962af: add hw buffered sampling")
Signed-off-by: Alexander Sverdlin <alexander.sverdlin@siemens.com>
Reviewed-by: Sean Nyekjaer <sean@geanix.com>
Link: https://lore.kernel.org/r/20240605203810.2908980-2-alexander.sverdlin@siemens.com
Signed-off-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 7387777aeb2c86e7af9ba13d04dce60e083dcb68)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I185d36ab03dea54f4f048e5cfa654792797507cf
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/121905
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>