Fix build error for IEE_SELINUX_P
security/selinux/include/security.h:21:10: fatal error: flask.h: No such file or directory
   21 | #include "flask.h"

Fixes: d8b9fa3e44da ("Add support for x86 CONFIG_IEE_SELINUX_P")
Signed-off-by: Jiajia Liu <liujiajia@kylinos.cn>