bcachefs: Fix compilation error for bch2_sb_member_alloc
Mainline: b161ca80968b55e551b82955e65264e8fc5f8660
From: v6.12-rc1
Severity: Moderate

task: 205710

Fix the following compilation error:

```
fs/bcachefs/sb-members.c: In function ‘bch2_sb_member_alloc’:
fs/bcachefs/sb-members.c:508:2: error: a label can only be part of a statement and a declaration is not a statement
  508 |  unsigned nr_devices = max_t(unsigned, dev_idx + 1, c->sb.nr_devices);
```

Fixes: a7d364a133c7 ("bcachefs: bch2_sb_member_alloc()")
Signed-off-by: Hongbo Li <lihongbo22@huawei.com>
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>
(backported from commit b161ca80968b55e551b82955e65264e8fc5f8660)

K2CI-Arch: All
Signed-off-by: Youling Tang <tangyouling@kylinos.cn>
Change-Id: Ia74cd8f5f3ce339fb7272b6e84e986ab758e4c3c
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/141775
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>