MIPS: cm: Fix warning if MIPS_CM is disabled
Mainline: b73c3ccdca95c237750c981054997c71d33e09d7
From: v6.15-rc1
Severity: Moderate

task: 460826

commit b73c3ccdca95c237750c981054997c71d33e09d7 upstream.

Commit e27fbe16af5c ("MIPS: cm: Detect CM quirks from device tree")
introduced

arch/mips/include/asm/mips-cm.h:119:13: error: ‘mips_cm_update_property’
	defined but not used [-Werror=unused-function]

Fix this by making empty function implementation inline

Fixes: e27fbe16af5c ("MIPS: cm: Detect CM quirks from device tree")
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 17d41d0f3a2683be946a0e2d134660481a250029)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I0db0bb271a817482d1c551bc4bc8d9b1d4e431ba
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/59980
Reviewed-by: 刘云 <liuyun01@kylinos.cn>