drm/tegra: hdmi: sor: Fix error: variable ‘j’ set but not used
Mainline: 1beee8d0c263b3e239c8d6616e4f8bb700bed658
From: v6.19-rc1
Severity: Moderate

task: 595983

[ Upstream commit 1beee8d0c263b3e239c8d6616e4f8bb700bed658 ]

The variable j is set, however never used in or outside the loop, thus
resulting in dead code.
Building with GCC 16 results in a build error due to
-Werror=unused-but-set-variable= enabled by default.
This patch clean up the dead code and fixes the build error.

Example build log:
drivers/gpu/drm/tegra/sor.c:1867:19: error: variable ‘j’ set but not used [-Werror=unused-but-set-variable=]
 1867 |         size_t i, j;
      |                   ^

Signed-off-by: Brahmajit Das <listout@listout.xyz>
Signed-off-by: Thierry Reding <treding@nvidia.com>
Link: https://lore.kernel.org/r/20250901212020.3757519-1-listout@listout.xyz
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit e120bae4c56d162f38e23ba67097077bf3e43cdd)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I172ed0affb5c0c8fde8975d3d9c9cf8dbed04afa
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/176587
Reviewed-by: 刘云 <liuyun01@kylinos.cn>