reset: hisilicon: hi6220: fix Wvoid-pointer-to-enum-cast warning
Mainline: b5ec294472794ed9ecba0cb4b8208372842e7e0d
From: v6.7-rc7
Severity: Moderate

task: 196396

[ Upstream commit b5ec294472794ed9ecba0cb4b8208372842e7e0d ]

'type' is an enum, thus cast of pointer on 64-bit compile test with W=1
causes:

  hi6220_reset.c:166:9: error: cast to smaller integer type 'enum hi6220_reset_ctrl_type' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230810091300.70197-1-krzysztof.kozlowski@linaro.org
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 88c38fd2f3e6b7897d0d5829aaee16b4da361e20)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: If8367bcc5f967c9dda7dc7fbf54ff63347de1e5e
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/93362
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>