tpm: export tpm2_sessions_init() to fix ibmvtpm building
Mainline: f168c000d27f8134160d4a52dfc474a948a3d7e9
From: v6.12-rc1
Severity: Low

task: 390743

Commit 08d08e2e9f0a ("tpm: ibmvtpm: Call tpm2_sessions_init() to
initialize session support") adds call to tpm2_sessions_init() in ibmvtpm,
which could be built as a module. However, tpm2_sessions_init() wasn't
exported, causing libmvtpm to fail to build as a module:

ERROR: modpost: "tpm2_sessions_init" [drivers/char/tpm/tpm_ibmvtpm.ko] undefined!

Export tpm2_sessions_init() to resolve the issue.

Cc: stable@vger.kernel.org # v6.10+
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202408051735.ZJkAPQ3b-lkp@intel.com/
Fixes: 08d08e2e9f0a ("tpm: ibmvtpm: Call tpm2_sessions_init() to initialize session support")
Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>
Reviewed-by: Stefan Berger <stefanb@linux.ibm.com>
Reviewed-by: Jarkko Sakkinen <jarkko@kernel.org>
Signed-off-by: Jarkko Sakkinen <jarkko@kernel.org>

(backported from commit f168c000d27f8134160d4a52dfc474a948a3d7e9)

Signed-off-by: shitao <shitao@kylinos.cn>
Change-Id: I234b1335556a14179ee289fb3980e150ff657388
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/148083
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>