ARM: davinci: always select CONFIG_CPU_ARM926T
Mainline: 40974ee421b4d1fc74ac733d86899ce1b83d8f65
From: v6.8-rc1
Severity: Moderate

task: 196396

[ Upstream commit 40974ee421b4d1fc74ac733d86899ce1b83d8f65 ]

The select was lost by accident during the multiplatform conversion.
Any davinci-only

arm-linux-gnueabi-ld: arch/arm/mach-davinci/sleep.o: in function `CACHE_FLUSH':
(.text+0x168): undefined reference to `arm926_flush_kern_cache_all'

Fixes: f962396ce292 ("ARM: davinci: support multiplatform build for ARM v5")
Acked-by: Bartosz Golaszewski <bartosz.golaszewski@linaro.org>
Link: https://lore.kernel.org/r/20240108110055.1531153-1-arnd@kernel.org
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit c5d4224a4d16dc7c7f34c5d8b6be3d65bbbdb822)

Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
Change-Id: I4585b2d0c1a3c0bdd582c1da9d6e73029f31be92
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/94285
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>