wifi: mt76: mt7996: fix mt7996_mcu_all_sta_info_event struct packing
Mainline: 2ee1c40daeb9a33e25c460bf87feca58e91af879
From: v6.8-rc1
Severity: Moderate

task: 456759

The internal struct and union inside mt7996_mcu_all_sta_info_event is
marked as being aligned, which conflicts with it being unaligned
within that structure:

drivers/net/wireless/mediatek/mt76/mt7996/mcu.h:165:2: error: field  within 'struct mt7996_mcu_all_sta_info_event' is less aligned than 'union mt7996_mcu_all_sta_info_event::(anonymous at ../drivers/net/wireless/mediatek/mt76/mt7996/mcu.h:165:2)' and is usually due to 'struct mt7996_mcu_all_sta_info_event' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]

Mark all three as being packed as well to ensure byte packing for
the entire thing.

Fixes: adde3eed4a75 ("wifi: mt76: mt7996: Add mcu commands for getting sta tx statistic")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Felix Fietkau <nbd@nbd.name>

(backported from commit 2ee1c40daeb9a33e25c460bf87feca58e91af879)

Signed-off-by: lilinmao <lilinmao@kylinos.cn>
Change-Id: I9dfe858cb304c6c49ad7379b9569cc5560ed36bc