KVM: fix kvm_mmu_memory_cache allocation warning
Mainline: ea3689d9df50c283cb5d647a74aa45e2cc3f8064
From: v6.9-rc1
Severity: Low

gcc-14 notices that the arguments to kvmalloc_array() are mixed up:

arch/x86/kvm/../../../virt/kvm/kvm_main.c: In function '__kvm_mmu_topup_memory_cache':
arch/x86/kvm/../../../virt/kvm/kvm_main.c:424:53: error: 'kvmalloc_array' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
  424 |                 mc->objects = kvmalloc_array(sizeof(void *), capacity, gfp);
      |                                                     ^~~~
arch/x86/kvm/../../../virt/kvm/kvm_main.c:424:53: note: earlier argument should specify number of elements, later size of each element

The code still works correctly, but the incorrect order prevents the compiler
from properly tracking the object sizes.

Fixes: 837f66c71207 ("KVM: Allow for different capacities in kvm_mmu_memory_cache structs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Marc Zyngier <maz@kernel.org>
Link: https://lore.kernel.org/r/20240212112419.1186065-1-arnd@kernel.org
Signed-off-by: Sean Christopherson <seanjc@google.com>

(backported from commit ea3689d9df50c283cb5d647a74aa45e2cc3f8064)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I7e84ddc37ca53628d8d97b8a04cf2ea871122aaf
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/55899
Tested-by: kernel-bot <kernel-bot@kylinos.cn>