KYLIN: av7110: fix build of array_index_nospec missing
Mainline: KYLIN-only
Severity: Low

drivers/staging/media/av7110/av7110_ca.c:39:14: error: implicit declaration of function ‘array_index_nospec’
   39 |   slot_num = array_index_nospec(data[2] - 1, MAX_CI_SLOTS);
      |              ^~~~~~~~~~~~~~~~~~
      |              array_index_mask_nospec

K2CI-Arch: All
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I270573146b0af76c292ded2c3ba39c9d5c23fcba
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/145024
Tested-by: k2ci <kernel-bot@kylinos.cn>