powerpc: Fix build error due to is_valid_bugaddr()
Mainline: f8d3555355653848082c351fa90775214fb8a4fa
From: v6.8-rc1
Severity: Moderate

task: 198520

[ Upstream commit f8d3555355653848082c351fa90775214fb8a4fa ]

With CONFIG_GENERIC_BUG=n the build fails with:

  arch/powerpc/kernel/traps.c:1442:5: error: no previous prototype for ‘is_valid_bugaddr’ [-Werror=missing-prototypes]
  1442 | int is_valid_bugaddr(unsigned long addr)
       |     ^~~~~~~~~~~~~~~~

The prototype is only defined, and the function is only needed, when
CONFIG_GENERIC_BUG=y, so move the implementation under that.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20231130114433.3053544-2-mpe@ellerman.id.au
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 641c67d59fd0deb2ce4079e53c9202f7a384b340)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Icbb572945475a23a6571be89d98734a14f9abf26
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/96492
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>