ASoC: qcom: Fix trivial code style issues
Mainline: bb3392453d3ba44e60b85381e3bfa3c551a44e5d
From: v6.8-rc1
Severity: Moderate

task: 460826

[ Upstream commit bb3392453d3ba44e60b85381e3bfa3c551a44e5d ]

Fix few trivial code style issues, pointed out by checkpatch, so they do
not get copied to new code (when old code is used as template):

  WARNING: Prefer "GPL" over "GPL v2" - see commit bf7fbeeae6db ("module: Cure the MODULE_LICENSE "GPL" vs. "GPL v2" bogosity")
  WARNING: function definition argument 'struct platform_device *' should also have an identifier name
  ERROR: code indent should use tabs where possible
  WARNING: please, no spaces at the start of a line
  WARNING: Missing a blank line after declarations
  WARNING: unnecessary whitespace before a quoted newline

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://msgid.link/r/20231204100048.211800-1-krzysztof.kozlowski@linaro.org
Signed-off-by: Mark Brown <broonie@kernel.org>
Stable-dep-of: a93dad6f4e6a ("ASoC: q6apm-dai: make use of q6apm_get_hw_pointer")
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 175cb0c28aea537f58371474a3aa50a98e9be9f1)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ie4b9c511e92ab3385cac83648c7cad4432f7328f
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/59813
Reviewed-by: 刘云 <liuyun01@kylinos.cn>