wifi: lib80211: remove unused variables iv32 and iv16
Mainline: e04b1973e2ab1e58a79156317b0dc25f848efdc5
From: v6.7-rc1
Severity: Moderate

task: 496179

clang with W=1 reports
net/wireless/lib80211_crypt_tkip.c:667:7: error: variable 'iv32'
  set but not used [-Werror,-Wunused-but-set-variable]
                u32 iv32 = tkey->tx_iv32;
                    ^
This variable not used so remove it.
Then remove a similar iv16 variable.
Change the comment because the unmodified value is returned.

Signed-off-by: Tom Rix <trix@redhat.com>
Reviewed-by: Simon Horman <simon.horman@corigine.com>
Link: https://lore.kernel.org/r/20230517123310.873023-1-trix@redhat.com
[change commit log wrt. 'length', add comment in the code]
Signed-off-by: Johannes Berg <johannes.berg@intel.com>

(backported from commit e04b1973e2ab1e58a79156317b0dc25f848efdc5)

K2CI-Arch: All
Change-Id: I7d813580a5aef3f73920fe24a9a72cef612a3bec
Signed-off-by: Yi Cong <yicong@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/91817
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>