KYLIN: unistd: add missing __NR_getrlimit system call number
Mainline: KYLIN-only
Severity: Moderate

Bug: #260873

The compilation error of qtwebengine is as follows:

third_party/lss/linux_syscall_support.h: In function 'int sys_getrlimit(int, kernel_rlimit*)':
third_party/lss/linux_syscall_support.h:2843:39: error: '__NR_getrlimit' was not declared in this scope
                                  : "i"(__NR_##name) , ## args

K2CI-Arch: Loongarch
Signed-off-by: Li ZhiGang <lizhigang@kylinos.cn>
Change-Id: Ib40ebb995580f253b1f9b333afb7ce6f8afbdaf0
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/133209
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>