phy: broadcom: ns-usb3: Fix Wvoid-pointer-to-enum-cast warning (again)
Mainline: fb21116099bbea1fc59efa9207e63c4be390ab72
From: v6.19-rc6
Severity: Moderate

task: 594541

[ Upstream commit fb21116099bbea1fc59efa9207e63c4be390ab72 ]

"family" is an enum, thus cast of pointer on 64-bit compile test with
clang W=1 causes:

  phy-bcm-ns-usb3.c:206:17: error: cast to smaller integer type 'enum bcm_ns_family' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]

This was already fixed in commit bd6e74a2f0a0 ("phy: broadcom: ns-usb3:
fix Wvoid-pointer-to-enum-cast warning") but then got bad in commit
21bf6fc47a1e ("phy: Use device_get_match_data()").

Note that after various discussions the preferred cast is via "unsigned
long", not "uintptr_t".

Fixes: 21bf6fc47a1e ("phy: Use device_get_match_data()")
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@oss.qualcomm.com>
Link: https://patch.msgid.link/20251224115533.154162-2-krzysztof.kozlowski@oss.qualcomm.com
Signed-off-by: Vinod Koul <vkoul@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 2a7ddafac3820e299c892d0c90d1fee3e929c207)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I3bd66d5655deeb96e5a072025fc04e6a976c2ef4
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/174483
Reviewed-by: 刘云 <liuyun01@kylinos.cn>