uacce: implement mremap in uacce_vm_ops to return -EPERM
Mainline: 02695347be532b628f22488300d40c4eba48b9b7
From: v6.19-rc7
Severity: Moderate
CVE: CVE-2026-23056

task: 593785

commit 02695347be532b628f22488300d40c4eba48b9b7 upstream.

The current uacce_vm_ops does not support the mremap operation of
vm_operations_struct. Implement .mremap to return -EPERM to remind
users.

The reason we need to explicitly disable mremap is that when the
driver does not implement .mremap, it uses the default mremap
method. This could lead to a risk scenario:

An application might first mmap address p1, then mremap to p2,
followed by munmap(p1), and finally munmap(p2). Since the default
mremap copies the original vma's vm_private_data (i.e., q) to the
new vma, both munmap operations would trigger vma_close, causing
q->qfr to be freed twice(qfr will be set to null here, so repeated
release is ok).

Fixes: 015d239ac014 ("uacce: add uacce driver")
Cc: stable@vger.kernel.org
Signed-off-by: Yang Shen <shenyang39@huawei.com>
Signed-off-by: Chenghai Huang <huangchenghai2@huawei.com>
Acked-by: Zhangfei Gao <zhangfei.gao@linaro.org>
Link: https://patch.msgid.link/20251202061256.4158641-4-huangchenghai2@huawei.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 4c042bc71474dbe417c268f4bfb8ec196f802f07)

K2CI-Arch: All
Cc: kernel-stable-team #2503 #2603 #KLAD
Change-Id: Ic00510bc9e9901f661426930a121683c69039060
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/173816
Reviewed-by: 刘云 <liuyun01@kylinos.cn>