KYLIN: virtio_vcpu_stall_detector: fix scoped_guard(spin_lock) undefined
Mainline: KYLIN-only
Severity: Low

include/linux/cleanup.h:87:3: error: implicit declaration of function ‘class_spin_lock_constructor’; did you mean ‘class_spinlock_constructor’? [-Werror=implicit-function-declaration]
   87 |   class_##_name##_constructor
      |   ^~~~~~
include/linux/cleanup.h:112:7: note: in expansion of macro ‘CLASS’
  112 |  for (CLASS(_name, scope)(args),     \
      |       ^~~~~
drivers/virtio/virtio_vcpu_stall_detector.c:91:2: note: in expansion of macro ‘scoped_guard’
   91 |  scoped_guard(spin_lock, &vcpu_stall->lock) {
      |  ^~~~~~~~~~~~
include/linux/cleanup.h:112:2: error: declaration of non-variable ‘class_spin_lock_constructor’ in ‘for’ loop initial declaration
  112 |  for (CLASS(_name, scope)(args),     \
      |  ^~~
drivers/virtio/virtio_vcpu_stall_detector.c:91:2: note: in expansion of macro ‘scoped_guard’
   91 |  scoped_guard(spin_lock, &vcpu_stall->lock) {

Reported-by: k2ci <kernel-bot@kylinos.cn>
Fixes: 7ddadde1aa48 ("KYLIN: vcpu_stall_detector: Convert spin_lock usage to guard(spin_lock)")
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I3c5271fdb1dae5e9cf00a85b670b2402ced8560d
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/125321
Tested-by: k2ci <kernel-bot@kylinos.cn>