mfd: stmpe-spi: Correct the name used in MODULE_DEVICE_TABLE
Mainline: 59d60c16ed41475f3b5f7b605e75fbf8e3628720
From: v6.16-rc1
Severity: Moderate

task: 482699

[ Upstream commit 59d60c16ed41475f3b5f7b605e75fbf8e3628720 ]

The name used in the macro does not exist.

drivers/mfd/stmpe-spi.c:132:26: error: use of undeclared identifier 'stmpe_id'
  132 | MODULE_DEVICE_TABLE(spi, stmpe_id);

Fixes: e789995d5c61 ("mfd: Add support for STMPE SPI interface")
Signed-off-by: Alexey Gladkov <legion@kernel.org>
Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/79d5a847303e45a46098f2d827d3d8a249a32be3.1745591072.git.legion@kernel.org
Signed-off-by: Lee Jones <lee@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit a20bbd91622f56f9b883a89506515c7c8bc0d24f)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I6c2dd5577a078796acba2a57e068d1c905146b8c
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/77083
Reviewed-by: 刘云 <liuyun01@kylinos.cn>