greybus: arche-ctrl: move device table to its right location
Mainline: 6a0b8c0da8d8d418cde6894a104cf74e6098ddfa
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 6a0b8c0da8d8d418cde6894a104cf74e6098ddfa ]

The arche-ctrl has two platform drivers and three of_device_id tables,
but one table is only used for the the module loader, while the other
two seem to be associated with their drivers.

This leads to a W=1 warning when the driver is built-in:

drivers/staging/greybus/arche-platform.c:623:34: error: 'arche_combined_id' defined but not used [-Werror=unused-const-variable=]
  623 | static const struct of_device_id arche_combined_id[] = {

Drop the extra table and register both tables that are actually
used as the ones for the module loader instead.

Fixes: 7b62b61c752a ("greybus: arche-ctrl: Don't expose driver internals to arche-platform driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240403080702.3509288-18-arnd@kernel.org
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 46c6fc133dc14aea071f66e47b874ba7f4c4c8f3)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I24a1d5f4324c1d3c287c9d0f228a2cd6eaa76791
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118328
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>