Input: ims-pcu - fix printf string overflow
Mainline: bf32bceedd0453c70d9d022e2e29f98e446d7161
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit bf32bceedd0453c70d9d022e2e29f98e446d7161 ]

clang warns about a string overflow in this driver

drivers/input/misc/ims-pcu.c:1802:2: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation]
drivers/input/misc/ims-pcu.c:1814:2: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation]

Make the buffer a little longer to ensure it always fits.

Fixes: 628329d52474 ("Input: add IMS Passenger Control Unit driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240326223825.4084412-7-arnd@kernel.org
Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit b003b8c15cbb70b7de7acc1dcb08a94f77a76e80)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I178912df30f594c04df6b691f30407166d5b15a6
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118453
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>