ext4: fix potential unnitialized variable
Mainline: 3f4830abd236d0428e50451e1ecb62e14c365e9b
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 3f4830abd236d0428e50451e1ecb62e14c365e9b ]

Smatch complains "err" can be uninitialized in the caller.

    fs/ext4/indirect.c:349 ext4_alloc_branch()
    error: uninitialized symbol 'err'.

Set the error to zero on the success path.

Fixes: 8016e29f4362 ("ext4: fast commit recovery path")
Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
Link: https://lore.kernel.org/r/363a4673-0fb8-4adf-b4fb-90a499077276@moroto.mountain
Signed-off-by: Theodore Ts'o <tytso@mit.edu>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 07fa88b0f340d71f1f7c8f250db642f338a61efa)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: If09b11b3eb47c7704aa38288162b2614bbb16cd0
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118275
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>