KYLIN: kasan: fix implicit declaration of function ‘alloc_pages_bulk’ in ___alloc_pages_bulk
Mainline: KYLIN-only
Severity: Low

Task: 543235

Fix x86/allyesconfig compilation error:
../mm/kasan/shadow.c: In function ‘___alloc_pages_bulk’:
../mm/kasan/shadow.c:368:32: error: implicit declaration of function ‘alloc_pages_bulk’;
did you mean ‘alloc_pages_mpol’? [-Werror=implicit-function-declaration]
368 | nr_populated = alloc_pages_bulk(gfp_mask, nr_pages, pages);
| ^~~~~~~~~~~~~~~~
| alloc_pages_mpol

Fixes: 06bd61e9f6c5 ("kasan: avoid sleepable page allocation from atomic context")
K2CI-Arch: All
Signed-off-by: liuqiqi <liuqiqi@kylinos.cn>
Change-Id: I0547da577a96500b6d3aa73fe639e78be788641b
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/134261
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>