caif: reduce stack size, again
Mainline: b630c781bcf6ff87657146661816d0d30a902139
From: v6.17-rc1
Severity: Moderate

task: 517535

[ Upstream commit b630c781bcf6ff87657146661816d0d30a902139 ]

I tried to fix the stack usage in this function a couple of years ago,
but there is still a problem with the latest gcc versions in some
configurations:

net/caif/cfctrl.c:553:1: error: the frame size of 1296 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Reduce this once again, with a separate cfctrl_link_setup() function that
holds the bulk of all the local variables. It also turns out that the
param[] array that takes up a large portion of the stack is write-only
and can be left out here.

Fixes: ce6289661b14 ("caif: reduce stack size with KASAN")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250620112244.3425554-1-arnd@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 655e3f51de5ad0cd3bc451891e41ce0513063f27)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I03993252691f83cee36c1a8176425b712ab3cfa6
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/100743
Reviewed-by: 刘云 <liuyun01@kylinos.cn>