apparmor: use the condition in AA_BUG_FMT even with debug disabled
Mainline: 67e370aa7f968f6a4f3573ed61a77b36d1b26475
From: v6.17-rc1
Severity: Moderate

task: 525135

[ Upstream commit 67e370aa7f968f6a4f3573ed61a77b36d1b26475 ]

This follows the established practice and fixes a build failure for me:
security/apparmor/file.c: In function ‘__file_sock_perm’:
security/apparmor/file.c:544:24: error: unused variable ‘sock’ [-Werror=unused-variable]
  544 |         struct socket *sock = (struct socket *) file->private_data;
      |                        ^~~~

Signed-off-by: Mateusz Guzik <mjguzik@gmail.com>
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit f8c001884bb4da56ce5617ed6c747ae61a17878f)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I18a84f354e594041a1c191836ea9d96e28e65411
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/109072
Reviewed-by: 刘云 <liuyun01@kylinos.cn>