MIPS: BCM47XX: Declare early_tlb_init() static
Mainline: d18419cd66835c29ac732624324b99b43f4cff1c
From: v6.10-rc1
Severity: Moderate

task: #218078

early_tlb_init() was local to file but not declared static,
leading to error:

arch/mips/bcm47xx/prom.c:126:6: error: no previous prototype \
	for ‘early_tlb_init’ [-Werror=missing-prototypes]
  126 | void early_tlb_init(void)
      |      ^~~~~~~~~~~~~~

Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>
Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Signed-off-by: luoqing <luoqing@kylinos.cn>
Change-Id: Iaefd9d836f14b029f92fc451f6bfd76b7f72dd70
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/122284
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>