enetc: avoid truncating error message
Mainline: 9046d581ed586f3c715357638ca12c0e84402002
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 9046d581ed586f3c715357638ca12c0e84402002 ]

As clang points out, the error message in enetc_setup_xdp_prog()
still does not fit in the buffer and will be truncated:

drivers/net/ethernet/freescale/enetc/enetc.c:2771:3: error: 'snprintf' will always be truncated; specified size is 80, but format string expands to at least 87 [-Werror,-Wformat-truncation]

Replace it with an even shorter message that should fit.

Fixes: f968c56417f0 ("net: enetc: shorten enetc_setup_xdp_prog() error message to fit NETLINK_MAX_FMTMSG_LEN")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240326223825.4084412-3-arnd@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 997a53102a3b5454e203071ae8f84205759e3f3c)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I46ac6924ae37b7aa170655ca3c7f21471eb5ee46
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118061
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>