selftests/landlock: Fix fs_test build with old libc
Mainline: 40b7835e74e0383be308d528c5e0e41b3bf72ade
From: v6.8-rc5
Severity: Moderate

task: 200497

[ Upstream commit 40b7835e74e0383be308d528c5e0e41b3bf72ade ]

One issue comes up while building selftest/landlock/fs_test on my side
(gcc 7.3/glibc-2.28/kernel-4.19).

gcc -Wall -O2 -isystem   fs_test.c -lcap -o selftests/landlock/fs_test
fs_test.c:4575:9: error: initializer element is not constant
  .mnt = mnt_tmp,
         ^~~~~~~

Signed-off-by: Hu Yadi <hu.yadi@h3c.com>
Suggested-by: Jiao <jiaoxupo@h3c.com>
Reviewed-by: Berlin <berlin@h3c.com>
Link: https://lore.kernel.org/r/20240124022908.42100-1-hu.yadi@h3c.com
Fixes: 04f9070e99a4 ("selftests/landlock: Add tests for pseudo filesystems")
[mic: Factor out mount's data string and make mnt_tmp static]
Signed-off-by: Mickaël Salaün <mic@digikod.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 854357db2f93c97365574fad6b5b31d12a13b24c)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I839ed87bac08f2386a20ca302e3ec3bfcea8de78
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/97824
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>