LoongArch: Eliminate superfluous get_numa_distances_cnt()
Mainline: a0d3c8bcb9206ac207c7ad3182027c6b0a1319bb
From: v6.14-rc6
Severity: Moderate

task: 458731

commit a0d3c8bcb9206ac207c7ad3182027c6b0a1319bb upstream.

In LoongArch, get_numa_distances_cnt() isn't in use, resulting in a
compiler warning.

Fix follow errors with clang-18 when W=1e:

arch/loongarch/kernel/acpi.c:259:28: error: unused function 'get_numa_distances_cnt' [-Werror,-Wunused-function]
  259 | static inline unsigned int get_numa_distances_cnt(struct acpi_table_slit *slit)
      |                            ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Link: https://lore.kernel.org/all/Z7bHPVUH4lAezk0E@kernel.org/
Signed-off-by: Yuli Wang <wangyuli@uniontech.com>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 37491e1dbb50fa3d37c0a4e33965d053ed47da0c)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I97a00d77ffc8ad8f4d91f1040608bc3bd42e463d
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/57473
Reviewed-by: 刘云 <liuyun01@kylinos.cn>