tools/perf: fix missing EM_SW64
Fix the following build error

util/dwarf-regs.c: In function ‘get_dwarf_regstr’:
util/dwarf-regs.c:61:14: error: ‘EM_SW64’ undeclared (first use in this function)
   61 |         case EM_SW64:

EM_SW64 definition is copied include/uapi/linux/elf-em.h

Signed-off-by: Jiajia Liu <liujiajia@kylinos.cn>