Revert "net: macb: Convert tasklet API to new bottom half workqueue mechanism"
Mainline: KYLIN-only
Severity: Moderate

task: 534399

This reverts commit 0d0c80760d987e781d9021815e9ed0a369031321.

This reverts commit caused the compilation to fail:
drivers/net/ethernet/cadence/macb_main.c: In function 'macb_hresp_error_task':
drivers/net/ethernet/cadence/macb_main.c:1801:27: error: implicit declaration
            of function 'from_work' [-Werror=implicit-function-declaration]
 1801 |         struct macb *bp = from_work(bp, work, hresp_err_bh_work);
      |                           ^~~~~~~~~
drivers/net/ethernet/cadence/macb_main.c:1801:47: error: 'hresp_err_bh_work'
            undeclared (first use in this function)
 1801 |         struct macb *bp = from_work(bp, work, hresp_err_bh_work);
      |                                               ^~~~~~~~~~~~~~~~~
drivers/net/ethernet/cadence/macb_main.c:1801:47: note: each undeclared
            identifier is reported only once for each function it appears in
drivers/net/ethernet/cadence/macb_main.c: In function 'macb_interrupt':
drivers/net/ethernet/cadence/macb_main.c:2003:36: error:
      'system_bh_wq' undeclared (first use in this function); did you mean 'system_wq'?
 2003 |                         queue_work(system_bh_wq, &bp->hresp_err_bh_work);

When backported dependency patches, there is a dependency patch is also
reverted in 6.6.y:
68f07f9acf8f (Revert "workqueue: Introduce struct wq_node_nr_active")
The reason is:
The workqueue patches backported to 6.6.y caused some reported
regressions, so revert them for now.

Cc: kernel-stable-team #KLAD
K2CI-Arch: All
Signed-off-by: Yi Cong <yicong@kylinos.cn>
Change-Id: Iaa80890a46d22a4c18c19cd1ef0b55e31786f065
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/122920
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>