x86/its: Fix build errors when CONFIG_MODULES=n
Mainline: 9f35e33144ae5377d6a8de86dd3bd4d995c6ac65
From: v6.15-rc6-52-g9f35e33144ae
Severity: Moderate

task: 464978

commit 9f35e33144ae5377d6a8de86dd3bd4d995c6ac65 upstream.

Fix several build errors when CONFIG_MODULES=n, including the following:

../arch/x86/kernel/alternative.c:195:25: error: incomplete definition of type 'struct module'
  195 |         for (int i = 0; i < mod->its_num_pages; i++) {

Fixes: 872df34d7c51 ("x86/its: Use dynamic thunks for indirect branches")
Cc: stable@vger.kernel.org
Signed-off-by: Eric Biggers <ebiggers@google.com>
Acked-by: Dave Hansen <dave.hansen@intel.com>
Tested-by: Steven Rostedt (Google) <rostedt@goodmis.org>
Reviewed-by: Alexandre Chartre <alexandre.chartre@oracle.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
[ pawan: backport: Bring ITS dynamic thunk code under CONFIG_MODULES ]
Signed-off-by: Pawan Gupta <pawan.kumar.gupta@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 9f69fe3888f643b16c35c8583036e94c5322ca61)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I46c93de2f81fd3523766542fe8eee17dfc9e650a
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/64512
Reviewed-by: 刘云 <liuyun01@kylinos.cn>