bpftool: Mount bpffs when pinmaps path not under the bpffs
Mainline: da5f8fd1f0d393d5eaaba9ad8c22d1c26bb2bf9b
From: v6.11-rc1
Severity: Moderate

task: 344423

[ Upstream commit da5f8fd1f0d393d5eaaba9ad8c22d1c26bb2bf9b ]

As Quentin said [0], BPF map pinning will fail if the pinmaps path is not
under the bpffs, like:

  libbpf: specified path /home/ubuntu/test/sock_ops_map is not on BPF FS
  Error: failed to pin all maps

  [0] https://github.com/libbpf/bpftool/issues/146

Fixes: 3767a94b3253 ("bpftool: add pinmaps argument to the load/loadall")
Signed-off-by: Tao Chen <chen.dylane@gmail.com>
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Tested-by: Quentin Monnet <qmo@kernel.org>
Reviewed-by: Quentin Monnet <qmo@kernel.org>
Link: https://lore.kernel.org/bpf/20240702131150.15622-1-chen.dylane@gmail.com
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 77bf25dab8ceea31428488637b272caa5708cf50)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I1a23a75770166894e4ddb347b99a5fcfda600074
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/127579
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>