perf test: Introduce --list-workloads to list the available workloads
Mainline: 13c138308d15cb194db53d0f24a4dd9de37193f3
From: v6.13-rc1
Severity: Low

Using it:

  $ perf test -w noplop
  No workload found: noplop
  $
  $ perf test -w
   Error: switch `w' requires a value
   Usage: perf test [<options>] [{list <test-name-fragment>|[<test-name-fragments>|<test-numbers>]}]

      -w, --workload <work>
                            workload to run for testing, use '--list-workloads' to list the available ones.
  $
  $ perf test --list-workloads
  noploop
  thloop
  leafloop
  sqrtloop
  brstack
  datasym
  landlock
  $

Would be good at some point to have a description in 'struct test_workload'.

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Reviewed-by: James Clark <james.clark@linaro.org>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Clark Williams <williams@redhat.com>
Link: https://lore.kernel.org/r/20241020021842.1752770-3-acme@kernel.org
Signed-off-by: Namhyung Kim <namhyung@kernel.org>

(backported from commit 13c138308d15cb194db53d0f24a4dd9de37193f3)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I869794d196ff1f2c92bb7461be13d7ccae1680b0
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/176505
Tested-by: kernel-bot <kernel-bot@kylinos.cn>