powerpc/fsl-soc: hide unused const variable
Mainline: 01acaf3aa75e1641442cc23d8fe0a7bb4226efb1
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 01acaf3aa75e1641442cc23d8fe0a7bb4226efb1 ]

vmpic_msi_feature is only used conditionally, which triggers a rare
-Werror=unused-const-variable= warning with gcc:

arch/powerpc/sysdev/fsl_msi.c:567:37: error: 'vmpic_msi_feature' defined but not used [-Werror=unused-const-variable=]
  567 | static const struct fsl_msi_feature vmpic_msi_feature =

Hide this one in the same #ifdef as the reference so we can turn on
the warning by default.

Fixes: 305bcf26128e ("powerpc/fsl-soc: use CONFIG_EPAPR_PARAVIRT for hcalls")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Christophe Leroy <christophe.leroy@csgroup.eu>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20240403080702.3509288-2-arnd@kernel.org
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit f0b4617d80c35ce60a3d9d5ead9f97f4058bc7b6)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Iacac5c2a9a135a8a8d548f76a32dc50af227c464
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118206
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>