KYLIN: crypto: hisilicon/sec2 - fix unused var err
Mainline: KYLIN-only
Severity: Low
KABI: Checked

Task: 431095

../drivers/crypto/hisilicon/sec2/sec_crypto.c: In function ‘sec_aead_callback’:
../drivers/crypto/hisilicon/sec2/sec_crypto.c:1671:25: error: unused variable ‘backlog_req’ [-Werror=unused-variable]
1671 | struct sec_req *backlog_req;
| ^~~~~~~~~~~
../drivers/crypto/hisilicon/sec2/sec_crypto.c:1670:30: error: unused variable ‘backlog_aead_req’ [-Werror=unused-variable]
1670 | struct aead_request *backlog_aead_req;
| ^~~~~~~~~~~~~~~~
../drivers/crypto/hisilicon/sec2/sec_crypto.c:1669:28: error: unused variable ‘qp_ctx’ [-Werror=unused-variable]
qp_ctx;
| ^~~~~~
cc1: all warnings being treated as errors

The historical patch introduced three lines of obsolete code during the conflict resolution
process.
Due to the patch being merged into the database, submit a new patch to remove excess code.

K2CI-Arch: Arm64
Fixes: bafdfa8ff50e ("crypto: hisilicon/sec2 - fix for aead icv error")
Signed-off-by: mengdehui <mengdehui@kylinos.cn>
Change-Id: I36d684aea70033b51eb45b9409fb9b5a6d091c96
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/157331
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: 陈刚 <chengang@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>