regulator: core: Stub devm_regulator_bulk_get_const() if !CONFIG_REGULATOR
Mainline: 1a5caec7f80ca2e659c03f45378ee26915f4eda2
From: v6.11-rc7
Severity: Moderate

task: 360875

[ Upstream commit 1a5caec7f80ca2e659c03f45378ee26915f4eda2 ]

When adding devm_regulator_bulk_get_const() I missed adding a stub for
when CONFIG_REGULATOR is not enabled. Under certain conditions (like
randconfig testing) this can cause the compiler to reports errors
like:

  error: implicit declaration of function 'devm_regulator_bulk_get_const';
  did you mean 'devm_regulator_bulk_get_enable'?

Add the stub.

Fixes: 1de452a0edda ("regulator: core: Allow drivers to define their init data as const")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202408301813.TesFuSbh-lkp@intel.com/
Cc: Neil Armstrong <neil.armstrong@linaro.org>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
Link: https://patch.msgid.link/20240830073511.1.Ib733229a8a19fad8179213c05e1af01b51e42328@changeid
Signed-off-by: Mark Brown <broonie@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit c5e236744db66c2eb02ac674c5e4cae0fa2abc1a)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ia8fec74b51aff085d347ee11b69acac7f01c0899
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/135449
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>