nfsd: Mark variable __maybe_unused to avoid W=1 build break
Mainline: ebae102897e760e9e6bc625f701dd666b2163bd1
From: v6.19-rc3
Severity: Moderate

task: 582447

commit ebae102897e760e9e6bc625f701dd666b2163bd1 upstream.

Clang is not happy about set but (in some cases) unused variable:

fs/nfsd/export.c:1027:17: error: variable 'inode' set but not used [-Werror,-Wunused-but-set-variable]

since it's used as a parameter to dprintk() which might be configured
a no-op. To avoid uglifying code with the specific ifdeffery just mark
the variable __maybe_unused.

The commit [1], which introduced this behaviour, is quite old and hence
the Fixes tag points to the first of the Git era.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/history/history.git/commit/?id=0431923fb7a1 [1]
Fixes: 1da177e4c3f4 ("Linux-2.6.12-rc2")
Cc: stable@vger.kernel.org
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Chuck Lever <chuck.lever@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 354834eb78670a3bf9978442a3829644bfb68597)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I4a06daefc09f780f8a4caecbf0076b7cd7b64ed9
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/164066
Reviewed-by: 刘云 <liuyun01@kylinos.cn>