selftests/cgroup: Fix compile error in test_cpu.c
Mainline: 11312c86f9d7d1bffe0587185934a7070ce9ec33
From: v6.13-rc1
Severity: Low

When compiling the cgroup selftests with the following command:

make -C tools/testing/selftests/cgroup/

the compiler complains as below:

test_cpu.c: In function ‘test_cpucg_nice’:
test_cpu.c:284:39: error: incompatible type for argument 2 of ‘hog_cpus_timed’
  284 |                 hog_cpus_timed(cpucg, param);
      |                                       ^~~~~
      |                                       |
      |                                       struct cpu_hog_func_param
test_cpu.c:132:53: note: expected ‘void *’ but argument is of type ‘struct cpu_hog_func_param’
  132 | static int hog_cpus_timed(const char *cgroup, void *arg)
      |                                               ~~~~~~^~~

Fix it by passing the address of param to hog_cpus_timed().

Fixes: 2e82c0d4562a ("cgroup/rstat: Selftests for niced CPU statistics")
Signed-off-by: Xiu Jianfeng <xiujianfeng@huawei.com>
Signed-off-by: Tejun Heo <tj@kernel.org>

(backported from commit 11312c86f9d7d1bffe0587185934a7070ce9ec33)

Signed-off-by: Yun Lu <luyun@kylinos.cn>
Change-Id: I45494b2bba6e63937bdb73db78039545d6dc1593
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/160172
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>