media: sta2x11: fix irq handler cast
Mainline: 3de49ae81c3a0f83a554ecbce4c08e019f30168e
From: v6.9-rc1
Severity: Moderate

task: 211935

[ Upstream commit 3de49ae81c3a0f83a554ecbce4c08e019f30168e ]

clang-16 warns about casting incompatible function pointers:

drivers/media/pci/sta2x11/sta2x11_vip.c:1057:6: error: cast from 'irqreturn_t (*)(int, struct sta2x11_vip *)' (aka 'enum irqreturn (*)(int, struct sta2x11_vip *)') to 'irq_handler_t' (aka 'enum irqreturn (*)(int, void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]

Change the prototype of the irq handler to the regular version with a
local variable to adjust the argument type.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Hans Verkuil <hverkuil-cisco@xs4all.nl>
[hverkuil: update argument documentation]
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit cb9420142e500f65ba6a6016c850bb4ce4dccdb1)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I526203fa6cba320ee4b5c1cbcd199490b205a3ac
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/107054
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>