platform/x86: thinkpad_acpi: Select INPUT_SPARSEKMAP in Kconfig
Mainline: 5d059bf2b1c4d5779a4c09ec418e40eded44a187
From: v6.10-rc2
Severity: Low

Now that drivers/platform/x86/thinkpad_acpi.c uses
sparse_keymap_report_event(), it must select INPUT_SPARSEKMAP in its
Kconfig option otherwise the build fails with:

  ld: vmlinux.o: in function `tpacpi_input_send_key':
  thinkpad_acpi.c:(.text+0xd4d27f): undefined reference to `sparse_keymap_report_event'
  ld: vmlinux.o: in function `hotkey_init':
  thinkpad_acpi.c:(.init.text+0x66cb6): undefined reference to `sparse_keymap_setup'

Fixes: 42f7b965de9d ("platform/x86: thinkpad_acpi: Switch to using sparse-keymap helpers")
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Link: https://lore.kernel.org/r/20240522074813.379b9fc2@gandalf.local.home
Signed-off-by: Hans de Goede <hdegoede@redhat.com>

(backported from commit 5d059bf2b1c4d5779a4c09ec418e40eded44a187)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I97a0640a7cfcfe8f055e690ed43a64a24b0da14e
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/69588
Tested-by: kernel-bot <kernel-bot@kylinos.cn>