cpufreq: intel_pstate: hide unused intel_pstate_cpu_oob_ids[]
Mainline: 8c556541a53848d6611ff8b5f9bf52e96c56f48e
From: v6.10-rc1
Severity: Moderate

task: 436775

The reference to this variable is hidden in an #ifdef:

drivers/cpufreq/intel_pstate.c:2440:32: error: 'intel_pstate_cpu_oob_ids' defined but not used [-Werror=unused-const-variable=]

Use the same check around the definition.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(backported from commit 8c556541a53848d6611ff8b5f9bf52e96c56f48e)

K2CI-Arch: Amd64
Signed-off-by: lifangxu <lifangxu@kylinos.cn>
Change-Id: Ia83bf15f1c111abdc001bf4517955603ebeae43b
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/159525
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>