LoongArch: KVM: Add returns to SIMD stubs
Mainline: 48ef9e87b407f89f230f804815af7ac2031ec17a
From: v6.8-rc2
Severity: Moderate

task: 217039

The stubs for kvm_own/lsx()/kvm_own_lasx() when CONFIG_CPU_HAS_LSX or
CONFIG_CPU_HAS_LASX is not defined should have a return value since they
return an int, so add "return -EINVAL;" to the stubs.
Fixes the build error:

In file included from ../arch/loongarch/include/asm/kvm_csr.h:12,
                 from ../arch/loongarch/kvm/interrupt.c:8:
../arch/loongarch/include/asm/kvm_vcpu.h: In function 'kvm_own_lasx':
../arch/loongarch/include/asm/kvm_vcpu.h:73:39: error: no return statement in function returning non-void [-Werror=return-type]
   73 | static inline int kvm_own_lasx(struct kvm_vcpu *vcpu) { }

Fixes: db1ecca22edf ("LoongArch: KVM: Add LSX (128bit SIMD) support")
Fixes: 118e10cd893d ("LoongArch: KVM: Add LASX (256bit SIMD) support")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>

(backported from commit 48ef9e87b407f89f230f804815af7ac2031ec17a)

K2CI-Arch: Loongarch
Signed-off-by: cuitao <cuitao@kylinos.cn>
Change-Id: I5ae1985bb8012ee1f92630d6a6fb33839acc3ffb
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/110205
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>