scsi: mpi3mr: Fix locking in an error path
Mainline: c733741ae1c3a5927f72664b0d760d5f4c14f96b
From: v6.15-rc1
Severity: Low

Make all error paths unlock rioc->bsg_cmds.mutex.

This patch fixes the following Clang -Wthread-safety errors:

drivers/scsi/mpi3mr/mpi3mr_app.c:2835:1: error: mutex 'mrioc->bsg_cmds.mutex' is not held on every path through here [-Werror,-Wthread-safety-analysis]
 2835 | }
      | ^
drivers/scsi/mpi3mr/mpi3mr_app.c:2332:6: note: mutex acquired here
 2332 |         if (mutex_lock_interruptible(&mrioc->bsg_cmds.mutex))
      |             ^
./include/linux/mutex.h:172:40: note: expanded from macro 'mutex_lock_interruptible'
  172 | #define mutex_lock_interruptible(lock) mutex_lock_interruptible_nested(lock, 0)
      |                                        ^

Cc: Sathya Prakash <sathya.prakash@broadcom.com>
Fixes: fb231d7deffb ("scsi: mpi3mr: Support for preallocation of SGL BSG data buffers part-2")
Signed-off-by: Bart Van Assche <bvanassche@acm.org>
Link: https://lore.kernel.org/r/20250210203936.2946494-2-bvanassche@acm.org
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

(backported from commit c733741ae1c3a5927f72664b0d760d5f4c14f96b)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I27f620f5816f6c04ee6e767772f754abbd66e5bb
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/67309
Tested-by: kernel-bot <kernel-bot@kylinos.cn>