leds: aw2013: Select missing dependency REGMAP_I2C
Mainline: 75469bb0537ad2ab0fc1fb6e534a79cfc03f3b3f
From: v6.8-rc1
Severity: Moderate

task: 196396

[ Upstream commit 75469bb0537ad2ab0fc1fb6e534a79cfc03f3b3f ]

The AW2013 driver uses devm_regmap_init_i2c, so REGMAP_I2C needs to
be selected.

Otherwise build process may fail with:
  ld: drivers/leds/leds-aw2013.o: in function `aw2013_probe':
    leds-aw2013.c:345: undefined reference to `__devm_regmap_init_i2c'

Signed-off-by: Dang Huynh <danct12@riseup.net>
Acked-by: Nikita Travkin <nikita@trvn.ru>
Fixes: 59ea3c9faf32 ("leds: add aw2013 driver")
Link: https://lore.kernel.org/r/20231103114203.1108922-1-danct12@riseup.net
Signed-off-by: Lee Jones <lee@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit ab27da1edb56725acb62b353a68c0c15ca20be19)

Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
Change-Id: Ia3e1429c6d31f03e497c01e6115ddb9bec98d7d3
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/94502
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>