hwmon: (occ) Mark occ_init_attribute() as __printf
Mainline: 831a2b27914cc880130ffe8fb8d1e65a5324d07f
From: v6.19
Severity: Moderate

task: 595741

[ Upstream commit 831a2b27914cc880130ffe8fb8d1e65a5324d07f ]

This is a printf-style function, which gcc -Werror=suggest-attribute=format
correctly points out:

drivers/hwmon/occ/common.c: In function 'occ_init_attribute':
drivers/hwmon/occ/common.c:761:9: error: function 'occ_init_attribute' might be a candidate for 'gnu_printf' format attribute [-Werror=suggest-attribute=format]

Add the attribute to avoid this warning and ensure any incorrect
format strings are detected here.

Fixes: 744c2fe950e9 ("hwmon: (occ) Rework attribute registration for stack usage")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20260203163440.2674340-1-arnd@kernel.org
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 8c934bafd10b968bc2be9ad83ab99710247ce251)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ibcaa41a9a20d2558fe340984c7d9bac84a6d5592
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/176373
Reviewed-by: 刘云 <liuyun01@kylinos.cn>