nvme: trace: avoid memcpy overflow warning
Mainline: a7de1dea76cd6a3707707af4ea2f8bc3cdeaeb11
From: v6.8-rc1
Severity: Moderate

task: 196396

[ Upstream commit a7de1dea76cd6a3707707af4ea2f8bc3cdeaeb11 ]

A previous patch introduced a struct_group() in nvme_common_command to help
stringop fortification figure out the length of the fields, but one function
is not currently using them:

In file included from drivers/nvme/target/core.c:7:
In file included from include/linux/string.h:254:
include/linux/fortify-string.h:592:4: error: call to '__read_overflow2_field' declared with 'warning' attribute: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
                        __read_overflow2_field(q_size_field, size);
                        ^

Change this one to use the correct field name to avoid the warning.

Fixes: 5c629dc9609dc ("nvme: use struct group for generic command dwords")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Keith Busch <kbusch@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 79e9dfd7f89a362d9a987b9aff10d3899de7ab23)

Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
Change-Id: I5d64b2602b886255ff9685d6f2790306e875050e
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/94576
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>