nvmet: re-fix tracing strncpy() warning
Mainline: 4ee7ffeb4ce50c80bc4504db6f39b25a2df6bcf4
From: v6.8-rc1
Severity: Moderate

task: 196396

[ Upstream commit 4ee7ffeb4ce50c80bc4504db6f39b25a2df6bcf4 ]

An earlier patch had tried to address a warning about a string copy with
missing zero termination:

drivers/nvme/target/trace.h:52:3: warning: ‘strncpy’ specified bound 32 equals destination size [-Wstringop-truncation]

The new version causes a different warning with some compiler versions, notably
gcc-9 and gcc-10, and also misses the zero padding that was apparently done
intentionally in the original code:

drivers/nvme/target/trace.h:56:2: error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]

Change it to use strscpy_pad() with the original length, which will give
a properly padded and zero-terminated string as well as avoiding the warning.

Fixes: d86481e924a7 ("nvmet: use min of device_path and disk len")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Keith Busch <kbusch@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 4652eb8176235351a650285f198fab647132ffc6)

Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
Change-Id: I042fc4598e6b97902d6c5adda8f14136d5be7d7a
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/94575
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>