crypto: ccp - drop platform ifdef checks
Mainline: 42c2d7d02977ef09d434b1f5b354f5bc6c1027ab
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 42c2d7d02977ef09d434b1f5b354f5bc6c1027ab ]

When both ACPI and OF are disabled, the dev_vdata variable is unused:

drivers/crypto/ccp/sp-platform.c:33:34: error: unused variable 'dev_vdata' [-Werror,-Wunused-const-variable]

This is not a useful configuration, and there is not much point in saving
a few bytes when only one of the two is enabled, so just remove all
these ifdef checks and rely on of_match_node() and acpi_match_device()
returning NULL when these subsystems are disabled.

Fixes: 6c5063434098 ("crypto: ccp - Add ACPI support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Tom Lendacky <thomas.lendacky@amd.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 4e9293d660bff93927d6de5015f1544e85fe133f)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Id5442eca95eef8ac9f9f1e30442f516ca0f60f68
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118021
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>