powerpc/64s: Fix CONFIG_NUMA=n build due to create_section_mapping()
Mainline: ede66cd22441820cbd399936bf84fdc4294bc7fa
From: v6.8-rc1
Severity: Moderate

task: 198520

[ Upstream commit ede66cd22441820cbd399936bf84fdc4294bc7fa ]

With CONFIG_NUMA=n the build fails with:

  arch/powerpc/mm/book3s64/pgtable.c:275:15: error: no previous prototype for ‘create_section_mapping’ [-Werror=missing-prototypes]
  275 | int __meminit create_section_mapping(unsigned long start, unsigned long end,
      |               ^~~~~~~~~~~~~~~~~~~~~~

That happens because the prototype for create_section_mapping() is in
asm/mmzone.h, but asm/mmzone.h is only included by linux/mmzone.h
when CONFIG_NUMA=y.

In fact the prototype is only needed by arch/powerpc/mm code, so move
the prototype into arch/powerpc/mm/mmu_decl.h, which also fixes the
build error.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20231129131919.2528517-5-mpe@ellerman.id.au
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 2074271ac73cd5f15ba5d9d6b5be7e1b54854c81)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ib968bdfab6857879f46b026d08987328a7ba4f65
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/96494
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>