vdso: Fix powerpc build U64_MAX undeclared error
Mainline: 8ff1e6c5aca5fd908e81c33c460c45f9555e1c22
From: v6.10-rc1
Severity: Low

U64_MAX is not in include/vdso/limits.h, although that isn't noticed on x86
because x86 includes include/linux/limits.h indirectly. However powerpc is
more selective, resulting in the following build error:

  In file included from <command-line>:
  lib/vdso/gettimeofday.c: In function 'vdso_calc_ns':
  lib/vdso/gettimeofday.c:11:33: error: 'U64_MAX' undeclared
     11 | # define VDSO_DELTA_MASK(vd)    U64_MAX
        |                                 ^~~~~~~

Use ULLONG_MAX instead which will work just as well and is in
include/vdso/limits.h.

Fixes: c8e3a8b6f2e6 ("vdso: Consolidate vdso_calc_delta()")
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Adrian Hunter <adrian.hunter@intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Link: https://lore.kernel.org/r/20240409062639.3393-1-adrian.hunter@intel.com
Closes: https://lore.kernel.org/all/20240409124905.6816db37@canb.auug.org.au/

(backported from commit 8ff1e6c5aca5fd908e81c33c460c45f9555e1c22)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Ia6f971e999d93e07c25a69805ee71a58789e2a60
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/135338
Tested-by: k2ci <kernel-bot@kylinos.cn>