media: st-delta: avoid excessive stack usage
Mainline: 5954ad7d1af92cb6244c5f31216e43af55febbb7
From: v6.18-rc1
Severity: Moderate

task: 542185

[ Upstream commit 5954ad7d1af92cb6244c5f31216e43af55febbb7 ]

Building with a reduced stack warning limit shows that delta_mjpeg_decode()
copies a giant structure to the stack each time but only uses three of
its members:

drivers/media/platform/st/sti/delta/delta-mjpeg-dec.c: In function 'delta_mjpeg_decode':
drivers/media/platform/st/sti/delta/delta-mjpeg-dec.c:427:1: error: the frame size of 1296 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Open-code the passing of the structure members that are actually used here.

Fixes: 433ff5b4a29b ("[media] st-delta: add mjpeg support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Hans Verkuil <hverkuil+cisco@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 30a4e81edb15329f795df0bd3d3693dd15ee2dd8)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I0bf9f47d410196fb2135120b10cf0f2d4ffd2152
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/128788
Reviewed-by: 刘云 <liuyun01@kylinos.cn>