perf lock contention: Fix a build error on 32-bit
Mainline: 29b8e94dcf2575c17541f843741ee96691ff1ded
From: v6.7-rc4
Severity: Moderate

task: 225023

Fix a build error on 32-bit system:

  util/bpf_lock_contention.c: In function 'lock_contention_get_name':
  util/bpf_lock_contention.c:253:50: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'u64 {aka long long unsigned int}' [-Werror=format=]
     snprintf(name_buf, sizeof(name_buf), "cgroup:%lu", cgrp_id);
                                                  ~~^
                                                  %llu
  cc1: all warnings being treated as errors

Fixes: d0c502e46e97 ("perf lock contention: Prepare to handle cgroups")
Signed-off-by: Yang Jihong <yangjihong1@huawei.com>
Acked-by: Namhyung Kim <namhyung@kernel.org>
Cc: avagin@google.com
Cc: daniel.diaz@linaro.org
Link: https://lore.kernel.org/r/20231118024858.1567039-3-yangjihong1@huawei.com
Signed-off-by: Namhyung Kim <namhyung@kernel.org>

(backported from commit 29b8e94dcf2575c17541f843741ee96691ff1ded)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Iaa29bbc680ef19b879a32f0459295be3d23a15d7
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/116207
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>