MIPS: RB532: Declare prom_setup_cmdline() and rb532_gpio_init() static
Mainline: b796d046433b2042577d8d6c9a5d366e39095c30
From: v6.10-rc1
Severity: Moderate

task: #218078

early_tlb_init() and rb532_gpio_init() were local to file but not declared
static, leading to error:

arch/mips/rb532/prom.c:49:13: error: no previous prototype 	\
	for ‘prom_setup_cmdline’ [-Werror=missing-prototypes]
   49 | void __init prom_setup_cmdline(void)
      |             ^~~~~~~~~~~~~~~~~~
arch/mips/rb532/gpio.c:200:12: error: no previous prototype 	\
	for ‘rb532_gpio_init’ [-Werror=missing-prototypes]
  200 | int __init rb532_gpio_init(void)
      |            ^~~~~~~~~~~~~~~

Signed-off-by: Yongzhen Zhang <zhangyongzhen@kylinos.cn>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Change-Id: I91770d129ea26a9aa9f35b8633808ba59b5cc296
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/122285
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>