kernel: trace: preemptirq_delay_test: use offstack cpu mask
Mainline: adc353c0bfb243ebfd29b6222fa3bf149169a6de
From: v6.17-rc1
Severity: Moderate

task: 517535

[ Upstream commit adc353c0bfb243ebfd29b6222fa3bf149169a6de ]

A CPU mask on the stack is broken for large values of CONFIG_NR_CPUS:

kernel/trace/preemptirq_delay_test.c: In function ‘preemptirq_delay_run’:
kernel/trace/preemptirq_delay_test.c:143:1: error: the frame size of 8512 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

Fall back to dynamic allocation here.

Cc: Masami Hiramatsu <mhiramat@kernel.org>
Cc: Song Chen <chensong_2000@189.cn>
Cc: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Link: https://lore.kernel.org/20250620111215.3365305-1-arnd@kernel.org
Fixes: 4b9091e1c194 ("kernel: trace: preemptirq_delay_test: add cpu affinity")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit adf2da0bf11969434fdacba0cfd94d63c2febfc7)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I4a9cfbceba253e1da01755cbed63faab60de7771
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/100817
Reviewed-by: 刘云 <liuyun01@kylinos.cn>