iommu: Fix compilation without CONFIG_IOMMU_INTEL
Mainline: 70bad345e622c23bb530016925c936ab04a646ac
From: v6.9-rc1
Severity: Moderate

task: 207205

[ Upstream commit 70bad345e622c23bb530016925c936ab04a646ac ]

When the kernel is comiled with CONFIG_IRQ_REMAP=y but without
CONFIG_IOMMU_INTEL compilation fails since commit def054b01a8678 with an
undefined reference to device_rbtree_find(). This patch makes sure that
intel specific code is only compiled with CONFIG_IOMMU_INTEL=y.

Signed-off-by: Bert Karwatzki <spasswolf@web.de>
Fixes: 80a9b50c0b9e ("iommu/vt-d: Improve ITE fault handling if target  device isn't present")
Reviewed-by: Lu Baolu <baolu.lu@linux.intel.com>
Link: https://lore.kernel.org/r/20240307194419.15801-1-spasswolf@web.de
Signed-off-by: Joerg Roedel <jroedel@suse.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 582a7eba2c259c6c0ff87c0336c4d0d67bb11945)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I6cd90a74a6f6333ddf4c87275dcd1a214a1942d3
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/100914
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>