mm: percpu: Include smp.h in alloc_tag.h
Mainline: 9b0abe7948364bd35fff2b202ee7f30a2fa73c53
From: v6.10-rc1
Severity: Moderate

task: 332844

percpu.h depends on smp.h, but doesn't include it directly because of
circular header dependency issues; percpu.h is needed in a bunch of low
level headers.

This fixes a randconfig build error on mips:

  include/linux/alloc_tag.h: In function '__alloc_tag_ref_set':
  include/asm-generic/percpu.h:31:40: error: implicit declaration of function 'raw_smp_processor_id' [-Werror=implicit-function-declaration]

Reported-by: kernel test robot <lkp@intel.com>
Fixes: 24e44cc22aa3 ("mm: percpu: enable per-cpu allocation tagging")
Closes: https://lore.kernel.org/oe-kbuild-all/202405210052.DIrMXJNz-lkp@intel.com/
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

(backported from commit 9b0abe7948364bd35fff2b202ee7f30a2fa73c53)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Ibc16f4787e80dc4e619bcc253323442d6e3f61ea
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/121790
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>