mm: Move lowmem_page_address() a little later
Mainline: 0871bc0129d403747ea0272a4384895d7ad37a6c
From: v6.9-rc4
Severity: Moderate

task: 217982

LoongArch will override page_to_virt() which use page_address() in the
KFENCE case (by defining WANT_PAGE_VIRTUAL/HASHED_PAGE_VIRTUAL). So move
lowmem_page_address() a little later to avoid such build errors:

error: implicit declaration of function 'page_address'.

Acked-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>

(backported from commit 0871bc0129d403747ea0272a4384895d7ad37a6c)

K2CI-Arch: Loongarch
Signed-off-by: George Guo <guodongtai@kylinos.cn>
Change-Id: I450efbf660efa04685731005bf4e3933bb41c443
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/111053
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>