sched: Put task_group::idle under CONFIG_GROUP_SCHED_WEIGHT
Mainline: 7ebd84d627e40cb9fb12b338588e81b6cca371e3
From: v6.12-rc1
Severity: Low

Task: #340825

When build with CONFIG_GROUP_SCHED_WEIGHT && !CONFIG_FAIR_GROUP_SCHED,
the idle member is not defined:

kernel/sched/ext.c:3701:16: error: 'struct task_group' has no member named 'idle'
  3701 |         if (!tg->idle)
       |                ^~

Fix this by putting 'idle' under new CONFIG_GROUP_SCHED_WEIGHT.

tj: Move idle field upward to avoid breaking up CONFIG_FAIR_GROUP_SCHED block.

Fixes: e179e80c5d4f ("sched: Introduce CONFIG_GROUP_SCHED_WEIGHT")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202409220859.UiCAoFOW-lkp@intel.com/
Signed-off-by: Yu Liao <liaoyu15@huawei.com>
Signed-off-by: Tejun Heo <tj@kernel.org>

K2CI-Arch: All
Signed-off-by: Bing Huang <huangbing@kylinos.cn>
Change-Id: I9d156d2aaff1be12bb44f42ceeb5ab4b321ced50
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/149239
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>