media: uvcvideo: Fix power line control for a Chicony camera
Mainline: dba3e701917a4cce92920f8ccb9fa4d4ee5ac07e
From: v6.8-rc1
Severity: Moderate

task: 198520

[ Upstream commit dba3e701917a4cce92920f8ccb9fa4d4ee5ac07e ]

The device does not implement the control properly.

Fixes v4l2-compliance error:

info: checking control 'Power Line Frequency' (0x00980918)
fail: v4l2-test-controls.cpp(552): could not set valid menu item 3

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 051400c305af326b57f9ee1bae996d025758cd4e)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ia798639ec3b2524a5f2c97fedfdd178eaed965a3
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/96663
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>