printk: Export match_devname_and_update_preferred_console()
Mainline: 3e5b2e81f17f176a4d451c1dd1794e64644319c4
From: v6.11
Severity: Low

task: 362331

When building serial_base as a module, modpost fails with the following
error message:

  ERROR: modpost: "match_devname_and_update_preferred_console"
  [drivers/tty/serial/serial_base.ko] undefined!

Export the symbol to allow using it from modules.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202409071312.qlwtTOS1-lkp@intel.com/
Fixes: 12c91cec3155 ("serial: core: Add serial_base_match_and_update_preferred_console()")
Signed-off-by: Yu Liao <liaoyu15@huawei.com>
Link: https://lore.kernel.org/r/20240909075652.747370-1-liaoyu15@huawei.com
Signed-off-by: Petr Mladek <pmladek@suse.com>

(backported from commit 3e5b2e81f17f176a4d451c1dd1794e64644319c4)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I710f2c0da4c2844d5963443e3bee68ebb4406f98
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/135914
Tested-by: k2ci <kernel-bot@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>