memory: tegra186-emc: drop unused to_tegra186_emc()
Mainline: 67dd9e861add38755a7c5d29e25dd0f6cb4116ab
From: v6.12-rc1
Severity: Moderate

task: 369107

commit 67dd9e861add38755a7c5d29e25dd0f6cb4116ab upstream.

to_tegra186_emc() is not used, W=1 builds:

  tegra186-emc.c:38:36: error: unused function 'to_tegra186_emc' [-Werror,-Wunused-function]

Fixes: 9a38cb27668e ("memory: tegra: Add interconnect support for DRAM scaling in Tegra234")
Cc: stable@vger.kernel.org
Link: https://lore.kernel.org/r/20240812123055.124123-1-krzysztof.kozlowski@linaro.org
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit ff580d01301e4bf1a3f0fbac51bf3ce83327c168)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I805cc6d9bc33d6dcd9a3dca173034c4804c2aaab
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/138079
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>