csky: fix arch_jump_label_transform_static override
Mainline: ca8e45c8048a2c9503c74751d25414601f730580
From: v6.8-rc1
Severity: Moderate

task: 196396

[ Upstream commit ca8e45c8048a2c9503c74751d25414601f730580 ]

The arch_jump_label_transform_static() function in csky was originally meant to
override the generic __weak function, but that got changed to an #ifndef check.

This showed up as a missing-prototype warning:
arch/csky/kernel/jump_label.c:43:6: error: no previous prototype for 'arch_jump_label_transform_static' [-Werror=missing-prototypes]

Change the method to use the new method of having a #define and a prototype
for the global function.

Fixes: 7e6b9db27de9 ("jump_label: make initial NOP patching the special case")
Fixes: 4e8bb4ba5a55 ("csky: Add jump-label implementation")
Reviewed-by: Guo Ren <guoren@kernel.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 060d799775f6bafbb877a517370fd4a778ec687a)

Signed-off-by: Geliang Tang <tanggeliang@kylinos.cn>
Change-Id: I30507e6c2bd4b12330cc06aa800c87ea5a3fda1a
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/94139
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>