x86/irq: Define trace events conditionally
Mainline: 9de7695925d5d2d2085681ba935857246eb2817d
From: v6.14-rc5
Severity: Moderate

task: 447495

[ Upstream commit 9de7695925d5d2d2085681ba935857246eb2817d ]

When both of X86_LOCAL_APIC and X86_THERMAL_VECTOR are disabled,
the irq tracing produces a W=1 build warning for the tracing
definitions:

  In file included from include/trace/trace_events.h:27,
                 from include/trace/define_trace.h:113,
                 from arch/x86/include/asm/trace/irq_vectors.h:383,
                 from arch/x86/kernel/irq.c:29:
  include/trace/stages/init.h:2:23: error: 'str__irq_vectors__trace_system_name' defined but not used [-Werror=unused-const-variable=]

Make the tracepoints conditional on the same symbosl that guard
their usage.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Link: https://lore.kernel.org/r/20250225213236.3141752-1-arnd@kernel.org
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit bb41ef31906e3faf1055cdb15384d9d3260e1325)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I4219ccaa94a8aaa9a8f315079b51f3931673373a
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/163876
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>