ata: sata_mv: Fix PCI device ID table declaration compilation warning
Mainline: 3137b83a90646917c90951d66489db466b4ae106
From: v6.9-rc3
Severity: Moderate

task: 211027

[ Upstream commit 3137b83a90646917c90951d66489db466b4ae106 ]

Building with W=1 shows a warning for an unused variable when CONFIG_PCI
is diabled:

drivers/ata/sata_mv.c:790:35: error: unused variable 'mv_pci_tbl' [-Werror,-Wunused-const-variable]
static const struct pci_device_id mv_pci_tbl[] = {

Move the table into the same block that containsn the pci_driver
definition.

Fixes: 7bb3c5290ca0 ("sata_mv: Remove PCI dependency")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Damien Le Moal <dlemoal@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit cbd080c308348ffac455e2833da2ee4f7fc59d5a)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Iecace1ce10e7ed5a6a4538305c9828b73d877265
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/106040
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>