powerpc/embedded6xx: Fix no previous prototype for avr_uart_send() etc.
Mainline: 20933531be0577cdd782216858c26150dbc7936f
From: v6.9-rc1
Severity: Moderate

task: 207205

[ Upstream commit 20933531be0577cdd782216858c26150dbc7936f ]

Move the prototypes into mpc10x.h which is included by all the relevant
C files, fixes:

  arch/powerpc/platforms/embedded6xx/ls_uart.c:59:6: error: no previous prototype for 'avr_uart_configure'
  arch/powerpc/platforms/embedded6xx/ls_uart.c:82:6: error: no previous prototype for 'avr_uart_send'

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20240305123410.3306253-1-mpe@ellerman.id.au
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit ffc331a37e29616238e5d391ed455fb01f424aa7)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I5406d38160262456f64d1570d34bb7b67fdb8ff8
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/101074
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>