MIPS: ip30: ip30-console: Add missing include
Mainline: 8de4ed75bd14ed197119ac509c6902a8561e0c1c
From: v6.11-rc1
Severity: Moderate

task: 344423

commit 8de4ed75bd14ed197119ac509c6902a8561e0c1c upstream.

Include linux/processor.h to fix build error:

arch/mips/sgi-ip30/ip30-console.c: In function ‘prom_putchar’:
arch/mips/sgi-ip30/ip30-console.c:21:17: error: implicit declaration of function ‘cpu_relax’ [-Werror=implicit-function-declaration]
   21 |                 cpu_relax();

Cc: stable@vger.kernel.org
Signed-off-by: Jiaxun Yang <jiaxun.yang@flygoat.com>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 97f099862aa4c865056046fce4e1b8ab2f18bd43)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I4b8c5657ec71f4289592eb727b5d14f146e3d1ba
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/127919
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>