memblock tests: fix undefined reference to `panic'
Mainline: e0f5a8e74be88f2476e58b25d3b49a9521bdc4ec
From: v6.9-rc4
Severity: Moderate

task: 220176

[ Upstream commit e0f5a8e74be88f2476e58b25d3b49a9521bdc4ec ]

commit e96c6b8f212a ("memblock: report failures when memblock_can_resize
is not set") introduced the usage of panic, which is not defined in
memblock test.

Let's define it directly in panic.h to fix it.

Signed-off-by: Wei Yang <richard.weiyang@gmail.com>
CC: Song Shuai <songshuaishuai@tinylab.org>
CC: Mike Rapoport <rppt@kernel.org>
Link: https://lore.kernel.org/r/20240402132701.29744-3-richard.weiyang@gmail.com
Signed-off-by: Mike Rapoport (IBM) <rppt@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 85907602db5fe0cb14d931005d5d63aa30ca24cc)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I8959278829956416f4d1d0f113d925c3567ec71b
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/112295
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>