drm/bridge: it6505: select REGMAP_I2C
Mainline: 21b137f651cf9d981e22d2c60a2a8105f50a6361
From: v6.18-rc1
Severity: Moderate

task: 542185

[ Upstream commit 21b137f651cf9d981e22d2c60a2a8105f50a6361 ]

Fix

  aarch64-linux-gnu-ld: drivers/gpu/drm/bridge/ite-it6505.o: in function `it6505_i2c_probe':
  ite-it6505.c:(.text+0x754): undefined reference to `__devm_regmap_init_i2c'

Signed-off-by: Chia-I Wu <olvaffe@gmail.com>
Fixes: b5c84a9edcd4 ("drm/bridge: add it6505 driver")
Reviewed-by: Chen-Yu Tsai <wenst@chromium.org>
Link: https://patch.msgid.link/20250610235825.3113075-1-olvaffe@gmail.com
Signed-off-by: Chen-Yu Tsai <wenst@chromium.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit d2e29c36eb5f9557ec402a06b84f44ac9b490d54)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ie85645cc5b7d9c87dcaca4b2790ea460d9820482
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/128774
Reviewed-by: 刘云 <liuyun01@kylinos.cn>