bcachefs: rename version -> bversion for big endian builds
Mainline: 2007d28ec0095c6db0a24fd8bb8fe280c65446cd
From: v6.12-rc2
Severity: Moderate

task: 205710

Builds on big endian systems fail as follows.

fs/bcachefs/bkey.h: In function 'bch2_bkey_format_add_key':
fs/bcachefs/bkey.h:557:41: error:
	'const struct bkey' has no member named 'bversion'

The original commit only renamed the variable for little endian builds.
Rename it for big endian builds as well to fix the problem.

Fixes: cf49f8a8c277 ("bcachefs: rename version -> bversion")
Cc: Kent Overstreet <kent.overstreet@linux.dev>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>

(backported from commit 2007d28ec0095c6db0a24fd8bb8fe280c65446cd)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I5c068d5df76d37d18e1b1e810e7e5f0231cd63dd
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/142411
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>