OPP: debugfs: Fix warning around icc_get_name()
Mainline: 28330ceb953e39880ea77da4895bb902a1244860
From: v6.9-rc1
Severity: Moderate

task: 207205

[ Upstream commit 28330ceb953e39880ea77da4895bb902a1244860 ]

If the kernel isn't built with interconnect support, icc_get_name()
returns NULL and we get following warning:

drivers/opp/debugfs.c: In function 'bw_name_read':
drivers/opp/debugfs.c:43:42: error: '%.62s' directive argument is null [-Werror=format-overflow=]
         i = scnprintf(buf, sizeof(buf), "%.62s\n", icc_get_name(path));

Fix it.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202402141313.81ltVF5g-lkp@intel.com/
Fixes: 0430b1d5704b0 ("opp: Expose bandwidth information via debugfs")
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>
Reviewed-by: Dhruva Gole <d-gole@ti.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit b64a1b4f4760f1a85607cfec2fcb6492a6863d79)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I55b6a267c1329e86567e4c529b9570496f204f59
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/100927
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>