libbpf: fix sym_is_subprog() logic for weak global subprogs
Mainline: 4073213488be542f563eb4b2457ab4cbcfc2b738
From: v6.13-rc1
Severity: Moderate

task: 398551

[ Upstream commit 4073213488be542f563eb4b2457ab4cbcfc2b738 ]

sym_is_subprog() is incorrectly rejecting relocations against *weak*
global subprogs. Fix that by realizing that STB_WEAK is also a global
function.

While it seems like verifier doesn't support taking an address of
non-static subprog right now, it's still best to fix support for it on
libbpf side, otherwise users will get a very confusing error during BPF
skeleton generation or static linking due to misinterpreted relocation:

  libbpf: prog 'handle_tp': bad map relo against 'foo' in section '.text'
  Error: failed to open BPF object file: Relocation failed

It's clearly not a map relocation, but is treated and reported as such
without this fix.

Fixes: 53eddb5e04ac ("libbpf: Support subprog address relocation")
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Link: https://lore.kernel.org/r/20241009011554.880168-1-andrii@kernel.org
Signed-off-by: Alexei Starovoitov <ast@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 36c79b9ff20a4999677c39226316b63fda999d7d)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I78603ba4dc6280e28a5afe2a82fe3e22c19c849b
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/148449
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>