arm: perf: Fix ARCH=arm build with GCC
Mainline: bb339db4d363c84e0a8d70827df591397ccd7312
From: v6.8-rc1
Severity: Moderate

task: 490891

LLVM ignores everything inside the if statement and doesn't generate
errors, but GCC doesn't ignore it, resulting in the following error:

  drivers/perf/arm_pmuv3.c: In function ‘armv8pmu_write_evtype’:
  include/linux/bits.h:34:29: error: left shift count >= width of type [-Werror=shift-count-overflow]
  34 |         (((~UL(0)) - (UL(1) << (l)) + 1) & \

Fix it by using GENMASK_ULL which doesn't overflow on arm32 (even though
the value is never used there).

Fixes: 3115ee021bfb ("arm64: perf: Include threshold control fields in PMEVTYPER mask")
Reported-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Closes: https://lore.kernel.org/linux-arm-kernel/20231215120817.h2f3akgv72zhrtqo@pengutronix.de/
Signed-off-by: James Clark <james.clark@arm.com>
Acked-by: Mark Rutland <mark.rutland@arm.com>
Reviewed-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
Link: https://lore.kernel.org/r/20231215175648.3397170-2-james.clark@arm.com
Signed-off-by: Will Deacon <will@kernel.org>

(backported from commit bb339db4d363c84e0a8d70827df591397ccd7312)

Signed-off-by: tanze <tanze@kylinos.cn>
Change-Id: Ia85d4b0b71371ca1d7818e4e0e5e28eeb4956ba1
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/87436
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 黄锦慧 <huangjinhui@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>