Revert "perf/arm_dmc620: Remove duplicate format attribute #defines"
Mainline: eb183b2cd0a6549992eca3c4ada0b1bc1d9340f5
From: v6.8-rc1
Severity: Moderate

task: 490891

This reverts commit a5f4ca68f348ac059efd6a3d7ad4040aed1c0818.

Pulling in the Arm-specific 'linux/perf/arm_pmu.h' header breaks the
allmodconfig build for x86:

> In file included from drivers/perf/arm_dmc620_pmu.c:26:
> include/linux/perf/arm_pmu.h:15:10: fatal error: asm/cputype.h: No such file or directory
>    15 | #include <asm/cputype.h>
>       |          ^~~~~~~~~~~~~~~

Just put things back like they were so that the driver can continue to
be compile-tested on a variety of architectures.

Link: https://lore.kernel.org/r/20231213100931.12d9d85e@canb.auug.org.au
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Will Deacon <will@kernel.org>

(backported from commit eb183b2cd0a6549992eca3c4ada0b1bc1d9340f5)

Signed-off-by: tanze <tanze@kylinos.cn>
Change-Id: Iaca7e1a9548e8ad54bb0b061a327fad5b50de545
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/87435
Reviewed-by: 黄锦慧 <huangjinhui@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>