cleanup: Remove address space of returned pointer
Mainline: f730fd535fc51573f982fad629f2fc6b4a0cde2f
From: v6.13-rc1
Severity: Moderate

task: 421187

[ Upstream commit f730fd535fc51573f982fad629f2fc6b4a0cde2f ]

Guard functions in local_lock.h are defined using DEFINE_GUARD() and
DEFINE_LOCK_GUARD_1() macros having lock type defined as pointer in
the percpu address space. The functions, defined by these macros
return value in generic address space, causing:

cleanup.h:157:18: error: return from pointer to non-enclosed address space

and

cleanup.h:214:18: error: return from pointer to non-enclosed address space

when strict percpu checks are enabled.

Add explicit casts to remove address space of the returned pointer.

Found by GCC's named address space checks.

Fixes: e4ab322fbaaa ("cleanup: Add conditional guard support")
Signed-off-by: Uros Bizjak <ubizjak@gmail.com>
Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
Link: https://lkml.kernel.org/r/20240819074124.143565-1-ubizjak@gmail.com
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 8c5ad189e90f5f1470c7c93b22320976dc1dc777)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I981c9f43e30be7ffda3a3af22adff2856c5e93b2
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/153262
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>