md: dm-zoned-target: Initialize return variable r to avoid uninitialized use
Mainline: 487767bff572d46f7c37ad846c4078f6d6c9cc55
From: v6.17-rc1
Severity: Moderate

task: 525135

[ Upstream commit 487767bff572d46f7c37ad846c4078f6d6c9cc55 ]

Fix Smatch-detected error:
drivers/md/dm-zoned-target.c:1073 dmz_iterate_devices()
error: uninitialized symbol 'r'.

Smatch detects a possible use of the uninitialized variable 'r' in
dmz_iterate_devices() because if dmz->nr_ddevs is zero, the loop is
skipped and 'r' is returned without being set, leading to undefined
behavior.

Initialize 'r' to 0 before the loop. This ensures that if there are no
devices to iterate over, the function still returns a defined value.

Signed-off-by: Purva Yeshi <purvayeshi550@gmail.com>
Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit d386c8e4e587c910b97caee9bd25732729bd7ed3)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I26618ca251621458b192d7a48ad8fab981815e52
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/109063
Reviewed-by: 刘云 <liuyun01@kylinos.cn>