iommu/vt-d: Fix constant-out-of-range warning
Mainline: 4578f989ed6b77c14af86bb882cc5ff0a46a69eb
From: v6.8-rc6
Severity: Moderate

task: 218851

On 32-bit builds, the vt-d driver causes a warning with clang:

drivers/iommu/intel/nested.c:112:13: error: result of comparison of constant 18446744073709551615 with expression of type 'unsigned long' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
  112 |         if (npages == U64_MAX)
      |             ~~~~~~ ^  ~~~~~~~

Make the variable a 64-bit type, which matches both the caller and the
use anyway.

Fixes: f6f3721244a8 ("iommu/vt-d: Add iotlb flush for nested domain")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240213095832.455245-1-arnd@kernel.org
Signed-off-by: Lu Baolu <baolu.lu@linux.intel.com>
Signed-off-by: Joerg Roedel <jroedel@suse.de>
(backported from commit 4578f989ed6b77c14af86bb882cc5ff0a46a69eb)

K2CI-Arch: Amd64
Signed-off-by: lifangxu <lifangxu@kylinos.cn>
Change-Id: Ic509600772f2d41d7c966bc39b5a3c807b7c2fcc
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/111336
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>