tools: ynl: fix build of the page-pool sample
Mainline: ee1eb9de81dbdbf078df659062e4df256a009627
From: v6.8-rc1
Severity: Important

task: 530755

The name of the "destroyed" field in the reply was not changed
in the sample after we started calling it "detach_time".

page-pool.c: In function ‘main’:
page-pool.c:84:33: error: ‘struct <anonymous>’ has no member named ‘destroyed’
   84 |                 if (pp->_present.destroyed)
      |                                 ^

Fixes: 637567e4a3ef ("tools: ynl: add sample for getting page-pool information")
Link: https://lore.kernel.org/r/20231129193622.2912353-2-kuba@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>

(backported from commit ee1eb9de81dbdbf078df659062e4df256a009627)

Change-Id: I00b202360c639a3573bd55a953130d6d280910ea
Signed-off-by: Guopeng Zhang <zhangguopeng@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/119939
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>