SUNWAY: fix compile error with CONFIG_SUNWAY_GED=m
Mainline: KYLIN-only
Severity: Low

Task: #382309

Fix the following errors:

ERROR: modpost: "unlock_device_hotplug" [drivers/misc/sunway-ged.ko] undefined!
ERROR: modpost: "__add_memory" [drivers/misc/sunway-ged.ko] undefined!
ERROR: modpost: "lock_device_hotplug" [drivers/misc/sunway-ged.ko] undefined!

Fixes: 51f31c3271e5 ("sw64: add memhotplug support for guest os")

K2CI-Arch: Sunway
Signed-off-by: Lei Yilong <leiyilong@wxiat.com>
Signed-off-by: liuyunchen <liuyunchen@kylinos.cn>
Change-Id: Ica7b28ea8885bea19d10838524b583d18342d240
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/66230
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>