memblock tests: fix undefined reference to `BIT'
Mainline: 592447f6cb3c20d606d6c5d8e6af68e99707b786
From: v6.9-rc4
Severity: Moderate

task: 220176

[ Upstream commit 592447f6cb3c20d606d6c5d8e6af68e99707b786 ]

commit 772dd0342727 ("mm: enumerate all gfp flags") define gfp flags
with the help of BIT, while gfp_types.h doesn't include header file for
the definition. This through an error on building memblock tests.

Let's include linux/bits.h to fix it.

Signed-off-by: Wei Yang <richard.weiyang@gmail.com>
CC: Suren Baghdasaryan <surenb@google.com>
CC: Michal Hocko <mhocko@suse.com>
Link: https://lore.kernel.org/r/20240402132701.29744-4-richard.weiyang@gmail.com
Signed-off-by: Mike Rapoport (IBM) <rppt@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 14e731533b395c8503545e4826392180632c24f2)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ib9adc44287e378bc8a1e69fc75e745a621bec987
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/112296
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>