KYLIN: Revert "KYLIN: selftests/bpf: fix the compilation errors caused by larchintrin.h"
Mainline: KYLIN-only
Severity: Low

task: 476205

This reverts commit c7e47a08f6ec49d049554a54250b5ce392f28181.
Use upstream version instead.

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Icc38f2017d659e7e13efed7de50774d77665249f
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/73303
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>