scsi: mpi3mr: Reduce stack usage in mpi3mr_refresh_sas_ports()
Mainline: 5cc2da0b60e5b4daf6cf7442ee66f1f91878c0b5
From: v6.8-rc7
Severity: Low

Doubling the number of PHYs also doubled the stack usage of this function,
exceeding the 32-bit limit of 1024 bytes:

drivers/scsi/mpi3mr/mpi3mr_transport.c: In function 'mpi3mr_refresh_sas_ports':
drivers/scsi/mpi3mr/mpi3mr_transport.c:1818:1: error: the frame size of 1636 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Since the sas_io_unit_pg0 structure is already allocated dynamically, use
the same method here. The size of the allocation can be smaller based on
the actual number of phys now, so use this as an upper bound.

Fixes: cb5b60894602 ("scsi: mpi3mr: Increase maximum number of PHYs to 64 from 32")
Reviewed-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>
Cc: Sathya Prakash Veerichetty <sathya.prakash@broadcom.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240123130754.2011469-1-arnd@kernel.org
Tested-by: John Garry <john.g.garry@oracle.com> #build only
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

(backported from commit 5cc2da0b60e5b4daf6cf7442ee66f1f91878c0b5)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I12925f624506970b752b8f48c5bf1d033aa486f1
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/65871
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 谭政 <tanzheng@kylinos.cn>