selftests/overlayfs: Fix build error on ppc64
Mainline: e8b8c5264d4ebd248f60a5cef077fe615806e7a0
From: v6.10-rc3
Severity: Low

task: 537001

Fix build error on ppc64:
  dev_in_maps.c: In function ‘get_file_dev_and_inode’:
  dev_in_maps.c:60:59: error: format ‘%llu’ expects argument of type
  ‘long long unsigned int *’, but argument 7 has type ‘__u64 *’ {aka ‘long
  unsigned int *’} [-Werror=format=]

By switching to unsigned long long for u64 for ppc64 builds.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

(backported from commit e8b8c5264d4ebd248f60a5cef077fe615806e7a0)

Change-Id: Id691308db8d4d1364dd06389e8ee0e64b5a6d8ce
Signed-off-by: Liu Hao <liuhao1@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/122736
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>