f2fs: Clean up errors in segment.h
Mainline: 37768434b7a7d00ac5a08b2c1d31aa7aaa0846a0
From: v6.7-rc1
Severity: Moderate

task: 227090

[ Upstream commit 37768434b7a7d00ac5a08b2c1d31aa7aaa0846a0 ]

Fix the following errors reported by checkpatch:

ERROR: spaces required around that ':' (ctx:VxW)

Signed-off-by: KaiLong Wang <wangkailong@jari.cn>
Reviewed-by: Chao Yu <chao@kernel.org>
Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
Stable-dep-of: aa4074e8fec4 ("f2fs: fix block migration when section is not aligned to pow2")
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 6496d63a164115bff77195e182ef668f4748bdeb)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I5b64e61e73175727cedce2612a75596faf39d7c6
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118394
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>