KYLIN: SUNWAY: Fix the error caused by the redefinition of page_to_phys
Mainline: KYLIN-only
Severity: Low

Task: #522745

Fix the error caused by the redefinition of page_to_phys
on the sw_64 architecture:
In file included from ../include/linux/io.h:14,
                 from ../arch/sw_64/lib/iomap_copy.c:3:
../arch/sw_64/include/asm/io.h:12: error: "page_to_phys" redefined [-Werror]
   12 | #define page_to_phys(page)      page_to_pa(page)
      |

K2CI-Arch: Sunway
Fixes: f16e516ba3a5 ("asm-generic: provide generic page_to_phys and phys_to_page implementations")
Reported-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I783a090c71b195d81b38cb8dbd2541b856e6aa0b
Signed-off-by: Qingshuang Fu <fuqingshuang@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/105501
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>