bpf: treewide: Align kfunc signatures to prog point-of-view
Mainline: cce4c40b960673f9e020835def310f1e89d3a940
From: v6.12-rc1
Severity: Low

Previously, kfunc declarations in bpf_kfuncs.h (and others) used "user
facing" types for kfuncs prototypes while the actual kfunc definitions
used "kernel facing" types. More specifically: bpf_dynptr vs
bpf_dynptr_kern, __sk_buff vs sk_buff, and xdp_md vs xdp_buff.

It wasn't an issue before, as the verifier allows aliased types.
However, since we are now generating kfunc prototypes in vmlinux.h (in
addition to keeping bpf_kfuncs.h around), this conflict creates
compilation errors.

Fix this conflict by using "user facing" types in kfunc definitions.
This results in more casts, but otherwise has no additional runtime
cost.

Note, similar to 5b268d1ebcdc ("bpf: Have bpf_rdonly_cast() take a const
pointer"), we also make kfuncs take const arguments where appropriate in
order to make the kfunc more permissive.

Signed-off-by: Daniel Xu <dxu@dxuuu.xyz>
Link: https://lore.kernel.org/r/b58346a63a0e66bc9b7504da751b526b0b189a67.1718207789.git.dxu@dxuuu.xyz
Signed-off-by: Alexei Starovoitov <ast@kernel.org>

(backported from commit cce4c40b960673f9e020835def310f1e89d3a940)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I124f44992d5619260028dc9317e87fc71d169aca
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/82081
Tested-by: kernel-bot <kernel-bot@kylinos.cn>