KYLIN: drm: cix: fix build error by -Werror=unused-variable
Mainline: KYLIN-only
Severity: Low

Task: #476119

K2CI reported:
../drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c: In function ‘linlondp_crtc_prepare’:
../drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c:127:34: error: unused variable ‘mode’ [-Werror=unused-variable]
127 | struct drm_display_mode *mode = &kcrtc_st->base.adjusted_mode;
| ^~~~
../drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c: In function ‘linlondp_crtc_mode_fixup’:
../drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c:547:23: error: unused variable ‘clk_rate’ [-Werror=unused-variable]
547 | unsigned long clk_rate;
| ^~~~~~~~
cc1: all warnings being treated as errors
CC drivers/gpu/drm/msm/disp/dpu1/dpu_hw_vbif.o
CC drivers/gpu/drm/arise/core/vidsch/vidsch_workerthread.o
CC drivers/acpi/container.o
CC drivers/gpu/drm/msm/disp/dpu1/dpu_hw_wb.o
make[8]: *** [../scripts/Makefile.build:243: drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.o] Error 1

K2CI-Arch: Arm64
Fixes: 60158fb (CIXTECH: drm: cix: add drm driver for CiX platforms)
Change-Id: I683cb5f0dca3d0b887dee6fa1945a44c92692ebc
Signed-off-by: lihaojie <lihaojie@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/76257
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>