mm/vmstat: fix a W=1 clang compiler warning
Mainline: 30c2de0a267c04046d89e678cc0067a9cfb455df
From: v6.13-rc4
Severity: Moderate

task: 415025

[ Upstream commit 30c2de0a267c04046d89e678cc0067a9cfb455df ]

Fix the following clang compiler warning that is reported if the kernel is
built with W=1:

./include/linux/vmstat.h:518:36: error: arithmetic between different enumeration types ('enum node_stat_item' and 'enum lru_list') [-Werror,-Wenum-enum-conversion]
  518 |         return node_stat_name(NR_LRU_BASE + lru) + 3; // skip "nr_"
      |                               ~~~~~~~~~~~ ^ ~~~

Link: https://lkml.kernel.org/r/20241212213126.1269116-1-bvanassche@acm.org
Fixes: 9d7ea9a297e6 ("mm/vmstat: add helpers to get vmstat item names for each enum type")
Signed-off-by: Bart Van Assche <bvanassche@acm.org>
Cc: Konstantin Khlebnikov <koct9i@gmail.com>
Cc: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 9ef08c3fe7643dab88cd16c4f15d7650289d5b31)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I38d50e6b4a04fc4d54527aa2becc6f8de1aa92ab
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/152287
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>