selftests/net: convert fib-onlink-tests.sh to run it in unique namespace
Mainline: 3a06833b2adc0a902f2469ad4ce41ccd64f1f3ab
From: v6.8-rc1
Severity: Moderate

task: 594541

[ Upstream commit 3a06833b2adc0a902f2469ad4ce41ccd64f1f3ab ]

Remove PEER_CMD, which is not used in this test

Here is the test result after conversion.

 ]# ./fib-onlink-tests.sh
 Error: ipv4: FIB table does not exist.
 Flush terminated
 Error: ipv6: FIB table does not exist.
 Flush terminated

 ########################################
 Configuring interfaces

   ...

     TEST: Gateway resolves to wrong nexthop device - VRF      [ OK ]

 Tests passed:  38
 Tests failed:   0

Acked-by: David Ahern <dsahern@kernel.org>
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
Link: https://lore.kernel.org/r/20231213060856.4030084-11-liuhangbin@gmail.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Stable-dep-of: 4f5f148dd7c0 ("selftests: net: fib-onlink-tests: Convert to use namespaces by default")
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 8ba4cf99c61cd0a022ce071c7cb6b8167b801b78)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ib53e7195f62a59d0317670aaa58bb95d138236ec
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/174552
Reviewed-by: 刘云 <liuyun01@kylinos.cn>