KYLIN: drivers/perf: fix compiling error due to irrational configuration dependencies
Mainline: KYLIN-only
Severity: Low

Task: 365109

This patch aims to fix a compiling error under 'allyesconfig' configuration:

drivers/perf/phytium/phytium_ddr_pmu.c:27:10: fatal error: asm/cputype.h: No such file or directory
   27 | #include <asm/cputype.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

The phytium_ddr_pmu source file is valid only for Phytium, but it would be compiled when COMPILE_TEST is configured even though it's on other architectures wheareas the header file it relies on is defined only under arm64 architecture. So, to avoiding compiling error on x86 architecture, we remove COMPILE_TEST for compiling phytium_ddr_pmu. Similarly, we also remove COMPILE_TEST for compiling phytium_pcie_pmu.

K2CI-Arch: All
Signed-off-by: Yunshui Jiang <jiangyunshui@kylinos.cn>
Change-Id: I3cf203802b748b2b1730901e13dea3d487c0ccde
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/136913
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>