SUNWAY: perf: fix compilation error
Mainline: KYLIN-only
Severity: Low

Task: #525815

Since the definition of EM_ARCH used under perf is inconsistent with the
kernel, fix it to make it consistent.

Cc: kernel-stable-team #KLAD
Cc: kernel-stable-team #2503
K2CI-Arch: All
Change-Id: I606ed6ddc38d713cdbb31ecb72d12bca5f40eee2
Signed-off-by: liuyunchen <liuyunchen@kylinos.cn>
Signed-off-by: He Chuyue <hechuyue@wxiat.com>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/145242
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>