SUNRPC: Fix -Wformat-truncation warning
Mainline: 9090a7f78623b5312562861d54a4476d905c7c4c
From: v6.12-rc1
Severity: Low

Increase size of the servername array to avoid truncated output warning.

net/sunrpc/clnt.c:582:75: error：‘%s’ directive output may be truncated
writing up to 107 bytes into a region of size 48
[-Werror=format-truncation=]
  582 |                   snprintf(servername, sizeof(servername), "%s",
      |                                                             ^~

net/sunrpc/clnt.c:582:33: note:‘snprintf’ output
between 1 and 108 bytes into a destination of size 48
  582 |                     snprintf(servername, sizeof(servername), "%s",
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  583 |                                          sun->sun_path);

Signed-off-by: Kunwu Chan <chentao@kylinos.cn>
Suggested-by: NeilBrown <neilb@suse.de>
Signed-off-by: Anna Schumaker <anna.schumaker@oracle.com>

(backported from commit 9090a7f78623b5312562861d54a4476d905c7c4c)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Icbb9d94625bdd9ad2742c56d26526a2c0ee078d4
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/142552
Tested-by: k2ci <kernel-bot@kylinos.cn>