ipv4/route: avoid unused-but-set-variable warning
Mainline: cf1b7201df59fb936f40f4a807433fe3f2ce310a
From: v6.9-rc4
Severity: Moderate

task: 213012

[ Upstream commit cf1b7201df59fb936f40f4a807433fe3f2ce310a ]

The log_martians variable is only used in an #ifdef, causing a 'make W=1'
warning with gcc:

net/ipv4/route.c: In function 'ip_rt_send_redirect':
net/ipv4/route.c:880:13: error: variable 'log_martians' set but not used [-Werror=unused-but-set-variable]

Change the #ifdef to an equivalent IS_ENABLED() to let the compiler
see where the variable is used.

Fixes: 30038fc61adf ("net: ip_rt_send_redirect() optimization")
Reviewed-by: David Ahern <dsahern@kernel.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Eric Dumazet <edumazet@google.com>
Link: https://lore.kernel.org/r/20240408074219.3030256-2-arnd@kernel.org
Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 5fd0b8b48696f1cfa483f1f73a6fa6fdf6efcef7)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I790d2197bb222d32b061142634ff12ce0138df30
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/107794
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>