KYLIN: crypto: Remove unused variable iv in zhaoxin sm4
Mainline: KYLIN-only
Severity: Low

task: 474205

as follow:
arch/x86/crypto/sm4-zhaoxin-gmi.c: In function ‘sm4_cipher_ofb’:
arch/x86/crypto/sm4-zhaoxin-gmi.c:354:6: error: unused variable ‘iv’ [-Werror=unused-variable]
  354 |  u8 *iv = NULL, *dst, *src;
      |      ^~

K2CI-Arch: Amd64
Reported-by: k2ci <kernel-bot@kylinos.cn>
Signed-off-by: jindongyang <jindongyang@kylinos.cn>
Change-Id: Ic9de68c9a7bf55e0c50317b1509a80acd2d63a3e
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/72445
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>