smb: server: Fix building with GCC 15
Mainline: e18655cf35a5958fbf4ae9ca3ebf28871a3a1801
From: v6.13-rc2
Severity: Moderate

task: 415025

[ Upstream commit e18655cf35a5958fbf4ae9ca3ebf28871a3a1801 ]

GCC 15 introduces -Werror=unterminated-string-initialization by default,
this results in the following build error

fs/smb/server/smb_common.c:21:35: error: initializer-string for array of 'char' is too long [-Werror=unterminated-string-ini
tialization]
   21 | static const char basechars[43] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-!@#$%";
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

To this we are replacing char basechars[43] with a character pointer
and then using strlen to get the length.

Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>
Acked-by: Namjae Jeon <linkinjeon@kernel.org>
Signed-off-by: Steve French <stfrench@microsoft.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 3ad1feaa0bd00d9a07c2138fcbc9236caca30b10)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I2eefa48e289f1cae3bba2f762b6182b02ec2279d
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/152321
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>