watchdog: lenovo_se30_wdt: include io.h for devm_ioremap()
Mainline: 0ccd5d56e6b2f342096a362ac24785d4be9c64a2
From: v6.15-rc1
Severity: Low

After merging the watchdog tree, today's linux-next build (x86_64
allmodconfig) failed like this:

drivers/watchdog/lenovo_se30_wdt.c: In function 'lenovo_se30_wdt_probe':
drivers/watchdog/lenovo_se30_wdt.c:272:31: error: implicit declaration of function 'devm_ioremap' [-Wimplicit-function-declaration]
  272 |         priv->shm_base_addr = devm_ioremap(dev, base_phys, SHM_WIN_SIZE);
      |                               ^~~~~~~~~~~~
drivers/watchdog/lenovo_se30_wdt.c:272:29: error: assignment to 'unsigned char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  272 |         priv->shm_base_addr = devm_ioremap(dev, base_phys, SHM_WIN_SIZE);
      |                             ^

Caused by commit

  c284153a2c55 ("watchdog: lenovo_se30_wdt: Watchdog driver for Lenovo SE30 platform")

Somewhere alogn the way a change to some include file means that
linux/io.h is no longer implicitly included.  I have added the following
patch for today.

Fixes: c284153a2c55 ("watchdog: lenovo_se30_wdt: Watchdog driver for Lenovo SE30 platform")
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Reviewed-by: Mark Pearson <mpearson-lenovo@squebb.ca>
Reviewed-by: Wim Van Sebroeck <wim@linux-watchdog.org>
Link: https://lore.kernel.org/r/20250311210305.3c5a2313@canb.auug.org.au
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Wim Van Sebroeck <wim@linux-watchdog.org>

(backported from commit 0ccd5d56e6b2f342096a362ac24785d4be9c64a2)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I2c3f7b9d0de7ca4b684dd6bf7984d1d7487d378c
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/67245
Tested-by: kernel-bot <kernel-bot@kylinos.cn>