net: xgene-v2: remove incorrect ACPI_PTR annotation
Mainline: 01358e8fe922f716c05d7864ac2213b2440026e7
From: v6.15-rc1
Severity: Moderate

task: 476205

[ Upstream commit 01358e8fe922f716c05d7864ac2213b2440026e7 ]

Building with W=1 shows a warning about xge_acpi_match being unused when
CONFIG_ACPI is disabled:

drivers/net/ethernet/apm/xgene-v2/main.c:723:36: error: unused variable 'xge_acpi_match' [-Werror,-Wunused-const-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250225163341.4168238-2-arnd@kernel.org
Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 7819a7dcf0412612782bbb12f7544b754b4c8c7e)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I494c8486d63674ceff33d73cb95052b3506dfe6b
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/72959
Reviewed-by: 刘云 <liuyun01@kylinos.cn>