bcachefs: Fix build error on weird gcc
Mainline: b912913613a1195ba86cbb1bc9b1c12b4c6c4a14
From: v6.7-rc1
Severity: Moderate

task: 205710

fixes
./include/linux/stddef.h:8:14: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]

Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>
(backported from commit b912913613a1195ba86cbb1bc9b1c12b4c6c4a14)

K2CI-Arch: All
Signed-off-by: Youling Tang <tangyouling@kylinos.cn>
Change-Id: I4c267ebf26f9b274df2d0fcea13b8bbee1902c04