media: mediatek: vcodec: mark vdec_vp9_slice_map_counts_eob_coef noinline
Mainline: 8b55f8818900c99dd4f55a59a103f5b29e41eb2c
From: v6.13-rc4
Severity: Moderate

task: 458731

commit 8b55f8818900c99dd4f55a59a103f5b29e41eb2c upstream.

With KASAN enabled, clang fails to optimize the inline version of
vdec_vp9_slice_map_counts_eob_coef() properly, leading to kilobytes
of temporary values spilled to the stack:

drivers/media/platform/mediatek/vcodec/decoder/vdec/vdec_vp9_req_lat_if.c:1526:12: error: stack frame size (2160) exceeds limit (2048) in 'vdec_vp9_slice_update_prob' [-Werror,-Wframe-larger-than]

This seems to affect all versions of clang including the latest (clang-20),
but the degree of stack overhead is different per release.

Marking the function as noinline_for_stack is harmless here and avoids
the problem completely.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Sebastian Fricke <sebastian.fricke@collabora.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit fa43166f2e8bac4616db14a4ef6e07eaea227ba0)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ifa253d3c81288dea7cd65da5b06c00ea595e164b
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/57347
Reviewed-by: 刘云 <liuyun01@kylinos.cn>