ext4: kunit: use dynamic inode allocation
Mainline: d60c53694c6ff560963590971720d632bb3d481e
From: v6.9-rc1
Severity: Low

task: 337979

Storing an inode structure on the stack pushes some functions over the warning
limit for stack frame size:

In file included from fs/ext4/mballoc.c:7039:
fs/ext4/mballoc-test.c:506:13: error: stack frame size (1032) exceeds limit (1024) in 'test_mark_diskspace_used' [-Werror,-Wframe-larger-than]
  506 | static void test_mark_diskspace_used(struct kunit *test)
      |             ^

Use kunit_kzalloc() for all inodes. There may be a better way to do it by
preallocating the inode, which would result in a larger rework.

Fixes: 2b81493f8eb6 ("ext4: Add unit test for ext4_mb_mark_diskspace_used")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Kemeng Shi <shikemeng@huaweicloud.com>
Link: https://lore.kernel.org/r/20240227161548.2929881-1-arnd@kernel.org
Signed-off-by: Theodore Ts'o <tytso@mit.edu>

(backported from commit d60c53694c6ff560963590971720d632bb3d481e)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I52e1ec39fa07a134eb71a250fd86a9cad69b7bcb
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/125151
Tested-by: k2ci <kernel-bot@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>