smb: client: fix smbdirect_recv_io leak in smbd_negotiate() error path
Mainline: daac51c7032036a0ca5f1aa419ad1b0471d1c6e0
From: v6.17-rc7
Severity: Moderate

task: 536679

[ Upstream commit daac51c7032036a0ca5f1aa419ad1b0471d1c6e0 ]

During tests of another unrelated patch I was able to trigger this
error: Objects remaining on __kmem_cache_shutdown()

Cc: Steve French <smfrench@gmail.com>
Cc: Tom Talpey <tom@talpey.com>
Cc: Long Li <longli@microsoft.com>
Cc: Namjae Jeon <linkinjeon@kernel.org>
Cc: linux-cifs@vger.kernel.org
Cc: samba-technical@lists.samba.org
Fixes: f198186aa9bb ("CIFS: SMBD: Establish SMB Direct connection")
Signed-off-by: Stefan Metzmacher <metze@samba.org>
Signed-off-by: Steve French <stfrench@microsoft.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit e7b7a93879558e77d950f1ff9a6f3daa385b33df)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I40731b7a5a466b77ec055629951c2a9b06002b7a
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/122277
Reviewed-by: 刘云 <liuyun01@kylinos.cn>