RDMA/core: reduce stack using in nldev_stat_get_doit()
Mainline: 43163f4c30f94d2103c948a247cdf2cda5068ca7
From: v6.17-rc1
Severity: Moderate

task: 525135

[ Upstream commit 43163f4c30f94d2103c948a247cdf2cda5068ca7 ]

In the s390 defconfig, gcc-10 and earlier end up inlining three functions
into nldev_stat_get_doit(), and each of them uses some 600 bytes of stack.

The result is a function with an overly large stack frame and a warning:

drivers/infiniband/core/nldev.c:2466:1: error: the frame size of 1720 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Mark the three functions noinline_for_stack to prevent this, ensuring
that only one copy of the nlattr array is on the stack of each function.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250620113335.3776965-1-arnd@kernel.org
Signed-off-by: Leon Romanovsky <leon@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 8c449e588d8188d065df59b33920d465c9900442)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I3a82897d5c5d1ae07255b7abc3f2a3a5fb5fdfd4
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/109047
Reviewed-by: 刘云 <liuyun01@kylinos.cn>