selftests/bpf: Fix compiling kfree_skb.c with musl-libc
Mainline: bae9a5ce7d3a9b3a9e07b31ab9e9c58450e3e9fd
From: v6.12-rc1
Severity: Moderate

task: 366821

[ Upstream commit bae9a5ce7d3a9b3a9e07b31ab9e9c58450e3e9fd ]

The GNU version of 'struct tcphdr' with member 'doff' is not exposed by
musl headers unless _GNU_SOURCE is defined. Add this definition to fix
errors seen compiling for mips64el/musl-libc:

  In file included from kfree_skb.c:2:
  kfree_skb.c: In function 'on_sample':
  kfree_skb.c:45:30: error: 'struct tcphdr' has no member named 'doff'
     45 |         if (CHECK(pkt_v6->tcp.doff != 5, "check_tcp",
        |                              ^

Fixes: 580d656d80cf ("selftests/bpf: Add kfree_skb raw_tp test")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Link: https://lore.kernel.org/bpf/e2d8cedc790959c10d6822a51f01a7a3616bea1b.1721713597.git.tony.ambardar@gmail.com
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 7d8d5840453aee9f867d57dd66ff7ca62abaede6)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ie7a2c05fa0c2502b3199e9213b262954fc2b266d
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/137277
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>