KVM: x86/mmu: Honor NEED_RESCHED when zapping rmaps and blocking is allowed
Mainline: 548f87f667a38ffeb2f021d9cfbc1f1b34fb4cb5
From: v6.12-rc1
Severity: Low

Convert kvm_unmap_gfn_range(), which is the helper that zaps rmap SPTEs in
response to an mmu_notifier invalidation, to use __kvm_rmap_zap_gfn_range()
and feed in range->may_block.  In other words, honor NEED_RESCHED by way of
cond_resched() when zapping rmaps.  This fixes a long-standing issue where
KVM could process an absurd number of rmap entries without ever yielding,
e.g. if an mmu_notifier fired on a PUD (or larger) range.

Opportunistically rename __kvm_zap_rmap() to kvm_zap_rmap(), and drop the
old kvm_zap_rmap().  Ideally, the shuffling would be done in a different
patch, but that just makes the compiler unhappy, e.g.

  arch/x86/kvm/mmu/mmu.c:1462:13: error: ‘kvm_zap_rmap’ defined but not used

Reported-by: Peter Xu <peterx@redhat.com>
Link: https://lore.kernel.org/r/20240809194335.1726916-14-seanjc@google.com
Signed-off-by: Sean Christopherson <seanjc@google.com>

(backported from commit 548f87f667a38ffeb2f021d9cfbc1f1b34fb4cb5)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I9c246d8951996fe9da0b78eaf0efb267184d176b
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/55906
Tested-by: kernel-bot <kernel-bot@kylinos.cn>