reset: fix BIT macro reference
Mainline: f3d8b64ee46c9b4b0b82b1a4642027728bac95b8
From: v6.19-rc1
Severity: Moderate

task: 582447

[ Upstream commit f3d8b64ee46c9b4b0b82b1a4642027728bac95b8 ]

RESET_CONTROL_FLAGS_BIT_* macros use BIT(), but reset.h does not
include bits.h. This causes compilation errors when including
reset.h standalone.

Include bits.h to make reset.h self-contained.

Suggested-by: Troy Mitchell <troy.mitchell@linux.dev>
Reviewed-by: Troy Mitchell <troy.mitchell@linux.dev>
Reviewed-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Encrow Thorne <jyc0019@gmail.com>
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit b1cad002d69aeed82c2917cbc6705cf2af370b09)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I0a0a59054df5297e9a15e66e797455c91010b85f
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/163988
Reviewed-by: 刘云 <liuyun01@kylinos.cn>