KYLIN: arm64: adapt ioremap_encrypted() to pre-pgprot_t ioremap_prot API
Mainline: KYLIN-only
Severity: Low

Upstream changed ioremap_prot() to take a pgprot_t instead of an
unsigned long, but our tree intentionally did not backport this API
change. As a result, newly imported patches that assume the pgprot_t
prototype cause build failures on arm64, since PAGE_KERNEL expands to a
pgprot_t while the local ioremap_prot() still expects an unsigned long.

This leads to errors such as:

  error: incompatible type for argument 3 of 'ioremap_prot'
  note: expected 'unsigned long' but argument is of type 'pgprot_t'

To keep our tree consistent with the original unsigned long-based
ioremap_prot() API, update ioremap_encrypted() to pass
pgprot_val(PAGE_KERNEL) instead of PAGE_KERNEL itself. This adapts the
newly imported code to our older interface without changing the global
API.

Once (or if) we adopt the upstream pgprot_t-based ioremap_prot()
interface, this helper should be updated accordingly.

K2CI-Arch: All
Fixes: 82ba8ef0eb1c ("arm64: Enable EFI secret area Securityfs support")
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I3f3ab5569533081a2cd8f6d66fec83884e600e4b
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/152486
Tested-by: kernel-bot <kernel-bot@kylinos.cn>