EDAC/device: Fix dev_set_name() format string
Mainline: 49472722d920ad39208a21eed1e8dc9038b4c2da
From: v6.15-rc1
Severity: Low

Passing a variable string as the format to dev_set_name() causes a W=1 warning:

  drivers/edac/edac_device.c:736:9: error: format not a string literal and no format arguments [-Werror=format-security]
    736 |         ret = dev_set_name(&ctx->dev, name);
        |         ^~~

Use a literal "%s" instead so the name can be the argument.

Fixes: db99ea5f2c03 ("EDAC: Add support for EDAC device features control")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
Link: https://lore.kernel.org/r/20250304143603.995820-1-arnd@kernel.org

(backported from commit 49472722d920ad39208a21eed1e8dc9038b4c2da)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I305a76a7ec3418dbdcf16905cde263640a261fc2
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/67235
Tested-by: kernel-bot <kernel-bot@kylinos.cn>