KYLIN: sw64: mm: fix pte_pgprot macro expansion compile error in hugetlbpage_c4.c
Mainline: KYLIN-only
Severity: Low

Task: #596037

sw_64 architecture compilation error:
In file included from ./include/linux/mm.h:30,
                 from arch/sw_64/mm/hugetlbpage_c4.c:9:
./include/linux/pgtable.h:2082:35: error: expected ')' before '{' token
 2082 | #define pte_pgprot(x) ((pgprot_t) {0})
      |                                   ^
arch/sw_64/mm/hugetlbpage_c4.c:42:24: note: in expansion of macro 'pte_pgprot'
   42 | static inline pgprot_t pte_pgprot(pte_t pte)
      |                        ^~~~~~~~~~
make[4]: *** [scripts/Makefile.build:243: arch/sw_64/mm/hugetlbpage_c4.o] Error 1
make[4]: *** Waiting for unfinished jobs....

By occupying the space in the arch/sw_64/mm/hugetlbpage_c4.c file
before defining the pte_pgprot function, the error can be resolved
by avoiding the default macro from taking effect.

K2CI-Arch: Sunway
Fixes: eb4d11bf8d66 ("SUNWAY: add build infrastructure")
Fixes: 7d1f17bed8f7 ("mm: always define pxx_pgprot()")
Change-Id: Ib5285a9de227ee57200f120e58e89a6d2f77ebb3
Signed-off-by: Qingshuang Fu <fuqingshuang@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/177521
Reviewed-by: 刘云 <liuyun01@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>