LoongArch: Include linux/sizes.h in addrspace.h to prevent build errors
Mainline: a07c772fa658645887119184de48b255bf19a46e
From: v6.9-rc4
Severity: Moderate

task: 217982

LoongArch's include/asm/addrspace.h uses SZ_32M and SZ_16K, so add
<linux/sizes.h> to provide those macros to prevent build errors:

In file included from ../arch/loongarch/include/asm/io.h:11,
                 from ../include/linux/io.h:13,
                 from ../include/linux/io-64-nonatomic-lo-hi.h:5,
                 from ../drivers/cxl/pci.c:4:
../include/asm-generic/io.h: In function 'ioport_map':
../arch/loongarch/include/asm/addrspace.h:124:25: error: 'SZ_32M' undeclared (first use in this function); did you mean 'PS_32M'?
  124 | #define PCI_IOSIZE      SZ_32M

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>

(backported from commit a07c772fa658645887119184de48b255bf19a46e)

K2CI-Arch: Loongarch
Signed-off-by: George Guo <guodongtai@kylinos.cn>
Change-Id: If041ffc8fb5b063cf4eb3312fe2b0a69964337b4
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/110858
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>