memblock tests: fix undefined reference to `early_pfn_to_nid'
Mainline: 7d8ed162e6a92268d4b2b84d364a931216102c8e
From: v6.9-rc4
Severity: Moderate

task: 220176

[ Upstream commit 7d8ed162e6a92268d4b2b84d364a931216102c8e ]

commit 6a9531c3a880 ("memblock: fix crash when reserved memory is not
added to memory") introduce the usage of early_pfn_to_nid, which is not
defined in memblock tests.

The original definition of early_pfn_to_nid is defined in mm.h, so let
add this in the corresponding mm.h.

Signed-off-by: Wei Yang <richard.weiyang@gmail.com>
CC: Yajun Deng <yajun.deng@linux.dev>
CC: Mike Rapoport <rppt@kernel.org>
Link: https://lore.kernel.org/r/20240402132701.29744-2-richard.weiyang@gmail.com
Signed-off-by: Mike Rapoport (IBM) <rppt@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 63e58e5aef2387010f7c433714c27915ce025832)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I5788cfc2a76af9bdf77e4b2d97d1143b21a861ef
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/112294
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>