KYLIN: Fix header file <asm/bitops.h> error
Mainline: KYLIN-only
Severity: Low

Task: #512033

Due to the header file #include <asm/bitops.h> used in the
include/linux/count_zeros.h file, but there is a direct prompt
"#error only <linux/bitops.h> can be included directly"
in the arch/x86/include/asm/bitops.h file, an error is generated:

In file included from ../include/linux/count_zeros.h:11,
                 from ../kernel/kexec_handover.c:12:
../arch/x86/include/asm/bitops.h:13:2: error: #error only <linux/bitops.h> can be included directly
   13 | #error only <linux/bitops.h> can be included directly
      |  ^~~~~

Fixes: a1164a3ac75f ("move count_zeroes.h out of asm-generic")
Change-Id: Ifdb74739581009aac1b3fa457543ac0c70e31f58
Signed-off-by: Qingshuang Fu <fuqingshuang@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/98064
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>