selftests/mm/mkdirty: fix memory leak in test_uffdio_copy()
Mainline: 7882d8fc8fe0c2b2a01f09e56edf82df6b3013fd
From: v6.14-rc1
Severity: Moderate

task: 436744

Release memory before exception branch returns to prevent memory leaks

Checking tools/testing/selftests/mm/mkdirty.c ...
tools/testing/selftests/mm/mkdirty.c:283:3: error: Memory leak: src [memleak]
  return;
  ^

Link: https://lkml.kernel.org/r/20250114023838.48589-1-liuye@kylinos.cn
Signed-off-by: liuye <liuye@kylinos.cn>
Reviewed-by: David Hildenbrand <david@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

(backported from commit 7882d8fc8fe0c2b2a01f09e56edf82df6b3013fd)

Signed-off-by: lihaofeng <lihaofeng@kylinos.cn>
Change-Id: Ia2693c581bb1fce42cdc9f4e8d069683ee9a4dc6
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/159402
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>