regmap: maple: Fix uninitialized symbol 'ret' warnings
Mainline: eaa03486d932572dfd1c5f64f9dfebe572ad88c0
From: v6.9-rc3
Severity: Moderate

task: 211027

[ Upstream commit eaa03486d932572dfd1c5f64f9dfebe572ad88c0 ]

Fix warnings reported by smatch by initializing local 'ret' variable
to 0.

drivers/base/regmap/regcache-maple.c:186 regcache_maple_drop()
error: uninitialized symbol 'ret'.
drivers/base/regmap/regcache-maple.c:290 regcache_maple_sync()
error: uninitialized symbol 'ret'.

Signed-off-by: Richard Fitzgerald <rf@opensource.cirrus.com>
Fixes: f033c26de5a5 ("regmap: Add maple tree based register cache")
Link: https://lore.kernel.org/r/20240329144630.1965159-1-rf@opensource.cirrus.com
Signed-off-by: Mark Brown <broonie@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit fce7a547b9c88a45d7481c0875f38a779c39d778)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I9af00402488f4653df5b33801c1d8dcefed792d7
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/106033
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>