cifs: fix potential null pointer use in destroy_workqueue in init_cifs error path
Mainline: 193cc89ea0ca1da311877d2b4bb5e9f03bcc82a2
From: v6.11-rc1
Severity: Moderate

task: 344423

commit 193cc89ea0ca1da311877d2b4bb5e9f03bcc82a2 upstream.

Dan Carpenter reported a Smack static checker warning:
   fs/smb/client/cifsfs.c:1981 init_cifs()
   error: we previously assumed 'serverclose_wq' could be null (see line 1895)

The patch which introduced the serverclose workqueue used the wrong
oredering in error paths in init_cifs() for freeing it on errors.

Fixes: 173217bd7336 ("smb3: retrying on failed server close")
Cc: stable@vger.kernel.org
Cc: Ritvik Budhiraja <rbudhiraja@microsoft.com>
Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Reviewed-by: Dan Carpenter <dan.carpenter@linaro.org>
Reviewed-by: David Howells <dhowell@redhat.com>
Signed-off-by: Steve French <stfrench@microsoft.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit 160235efb4f9b55212dedff5de0094c606c4b303)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: If1b19f659ce7ca9abe20e527b32b917b23fcb891
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/127818
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>