fbdev: shmobile: fix snprintf truncation
Mainline: 26c8cfb9d1e4b252336d23dd5127a8cbed414a32
From: v6.10-rc1
Severity: Moderate

task: 227090

[ Upstream commit 26c8cfb9d1e4b252336d23dd5127a8cbed414a32 ]

The name of the overlay does not fit into the fixed-length field:

drivers/video/fbdev/sh_mobile_lcdcfb.c:1577:2: error: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 25

Make it short enough by changing the string.

Fixes: c5deac3c9b22 ("fbdev: sh_mobile_lcdc: Implement overlays support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Laurent Pinchart <laurent.pinchart+renesas@ideasonboard.com>
Signed-off-by: Helge Deller <deller@gmx.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 4a1dc972127517c80d2d6d629327727a699f0b84)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ieec096ad0e5cc2b71a5a3ca5c7a08011a94ed748
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/118202
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>