bcachefs: Fix -Wself-assign
Mainline: 265cc423155d56030e44068680085adb59800326
From: v6.7-rc1
Severity: Moderate

task: 205710

Fixes the following observed error reported by Nathan on IRC.

  fs/bcachefs/io_misc.c:467:6: error: explicitly assigning value of
  variable of type 'int' to itself [-Werror,-Wself-assign]
    467 |         ret = ret;
        |         ~~~ ^ ~~~

Reported-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>
(backported from commit 265cc423155d56030e44068680085adb59800326)

K2CI-Arch: All
Signed-off-by: Youling Tang <tangyouling@kylinos.cn>
Change-Id: Ibe7ecdcd8e17f0a647bd9477e16272fd6b9697e9