parisc: don't reference obsolete termio struct for TC* constants
Mainline: 8ec5a066f88f89bd52094ba18792b34c49dcd55a
From: v6.18-rc1
Severity: Moderate

task: 543279

commit 8ec5a066f88f89bd52094ba18792b34c49dcd55a upstream.

Similar in nature to ab107276607af90b13a5994997e19b7b9731e251. glibc-2.42
drops the legacy termio struct, but the ioctls.h header still defines some
TC* constants in terms of termio (via sizeof). Hardcode the values instead.

This fixes building Python for example, which falls over like:
  ./Modules/termios.c:1119:16: error: invalid application of 'sizeof' to incomplete type 'struct termio'

Link: https://bugs.gentoo.org/961769
Link: https://bugs.gentoo.org/962600
Co-authored-by: Stian Halseth <stian@itx.no>
Cc: stable@vger.kernel.org
Signed-off-by: Sam James <sam@gentoo.org>
Signed-off-by: Helge Deller <deller@gmx.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(backported from commit eb67aaf2c2f3d3fcdf49a8a83908aac955fe8178)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I11d3238d57b71ed0f86ae0ae6be4e35fb7c0fa05
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/129893
Reviewed-by: 刘云 <liuyun01@kylinos.cn>