KYLIN: hardware_message: fix comparison always true for the address
Mainline: KYLIN-only
Severity: Low

Task: 339361

../kernel/hardware_message.c: In function ‘mark_partner_supported_module’:
../kernel/hardware_message.c:303:21: error: the comparison will always evaluate as ‘true’ for the address of ‘name’ will never be NULL [-Werror=address]
  303 |         if (!mod || !mod->name)
      |                     ^
In file included from ../kernel/hardware_message.c:23:
../include/linux/module.h:415:14: note: ‘name’ declared here
  415 |         char name[MODULE_NAME_LEN];
      |              ^~~~
cc1: all warnings being treated as errors
make[4]: *** [../scripts/Makefile.build:243: kernel/hardware_message.o] Error 1

K2CI-Arch: All
Fixes: db0fb28a63df ("KYLIN: hardware_message: Introduce mark_partner_supported_module function")
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I1ce0bd3429a959bf7ed77784721bf4b27b1e208c
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/125467
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>