LoongArch: Replace mp_ops with smp_ops in paravirt.c
struct smp_ops smp_ops is introduced in

  commit 88b9f47ed60a ("LOONGSON: LoongArch/smp: Refine some ipi functions on LoongArch platform")

but mp_ops is used in

  commit 158974f4e420 ("LoongArch: KVM: Add PV IPI support on guest side")

when compiling with CONFIG_PARAVIRT, there exists the following error,
replace mp_ops with smp_ops to fix it.

  CC      arch/loongarch/kernel/paravirt.o
arch/loongarch/kernel/paravirt.c: In function ‘pv_ipi_init’:
arch/loongarch/kernel/paravirt.c:187:9: error: ‘mp_ops’ undeclared (first use in this function); did you mean ‘smp_ops’?
  187 |         mp_ops.init_ipi         = pv_init_ipi;
      |         ^~~~~~
      |         smp_ops
arch/loongarch/kernel/paravirt.c:187:9: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [scripts/Makefile.build:243: arch/loongarch/kernel/paravirt.o] Error 1

Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>