KVM: guest-memfd: fix unused-function warning
Mainline: 80583d0cfd8ff44d60a5fa76a6bf3c08eb67c328
From: v6.8-rc1
Severity: Low

Task: #216854

With migration disabled, one function becomes unused:

virt/kvm/guest_memfd.c:262:12: error: 'kvm_gmem_migrate_folio' defined but not used [-Werror=unused-function]
  262 | static int kvm_gmem_migrate_folio(struct address_space *mapping,
      |            ^~~~~~~~~~~~~~~~~~~~~~

Remove the #ifdef around the reference so that fallback_migrate_folio()
is never used.  The gmem implementation of the hook is trivial; since
the gmem mapping is unmovable, the pages should not be migrated anyway.

Fixes: a7800aa80ea4 ("KVM: Add KVM_CREATE_GUEST_MEMFD ioctl() for guest-specific backing memory")
Reported-by: Arnd Bergmann <arnd@arndb.de>
Suggested-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

(backported from commit 80583d0cfd8ff44d60a5fa76a6bf3c08eb67c328)

Signed-off-by: Kunwu Chan <chentao@kylinos.cn>
Change-Id: I41a630d6e09cdadbc86bac3898caa4e1e9ac5c1e
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/112160
Code-Style: k2ci <kernel-bot@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>