SUNWAY: fix compilation issues
Mainline: KYLIN-only
Severity: Low

Task: #382309

Current code causes a compilation error when the CONFIG_PM is not
selected. This commit modifies the relevant code logic to fix this
issue.

K2CI-Arch: Sunway
Signed-off-by: Wang Yicheng <wangyicheng@wxiat.com>
Signed-off-by: liuyunchen <liuyunchen@kylinos.cn>
Change-Id: Ia183ccc6f67602eee9c615b002122da3841f1b5a
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/67768
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>