sched: Remove never used code in mm_cid_get()
Mainline: 53abe3e1c154628cc74e33a1bfcd865656e433a5
From: v6.18-rc3
Severity: Moderate

task: 547259

[ Upstream commit 53abe3e1c154628cc74e33a1bfcd865656e433a5 ]

Clang is not happy with set but unused variable (this is visible
with `make W=1` build:

  kernel/sched/sched.h:3744:18: error: variable 'cpumask' set but not used [-Werror,-Wunused-but-set-variable]

It seems like the variable was never used along with the assignment
that does not have side effects as far as I can see.  Remove those
altogether.

Fixes: 223baf9d17f2 ("sched: Fix performance regression introduced by mm_cid")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Tested-by: Eric Biggers <ebiggers@kernel.org>
Reviewed-by: Breno Leitao <leitao@debian.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 6d63703bec0c1fb3c68b47811f6d977183badf89)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I269173e11a5095878bb48bd21f5de814f158e34f
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/134761
Reviewed-by: 刘云 <liuyun01@kylinos.cn>