arm64: Kconfig: Fix dependencies to enable ACPI_HOTPLUG_CPU
Mainline: 46800e38ef0e45a73839ded0347885ada2b4f7bb
From: v6.10-rc3-20-g46800e38ef0e
Severity: Moderate

task: 327586

Both ACPI_PROCESSOR and HOTPLUG_CPU are needed by ACPI_HOTPLUG_CPU.
Otherwise, we can have compiling error with the following configurations.

  CONFIG_HOTPLUG_CPU=n
  CONFIG_ACPI_PROCESSOR=y
  CONFIG_ACPI_HOTPLUG_CPU=y

  arch/arm64/kernel/smp.c: In function ‘arch_unregister_cpu’:
  arch/arm64/kernel/smp.c:563:9: error: implicit declaration of  \
  function ‘unregister_cpu’; did you mean ‘register_cpu’?        \
  [-Werror=implicit-function-declaration]
  563 |         unregister_cpu(c);
      |         ^~~~~~~~~~~~~~
      |         register_cpu

Fix it by enabling ACPI_HOTPLUG_CPU when both ACPI_PROCESSOR and
HOTPLUG_CPU are enabled, consistent with other architectures like
x86 and loongarch.

Fixes: 9d0873892f4d ("arm64: Kconfig: Enable hotplug CPU on arm64 if ACPI_PROCESSOR is enabled.")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202406300437.XnuW0n34-lkp@intel.com/
Signed-off-by: Gavin Shan <gshan@redhat.com>
Acked-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
Link: https://lore.kernel.org/r/20240701001132.1585153-1-gshan@redhat.com
Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

(backported from commit 46800e38ef0e45a73839ded0347885ada2b4f7bb)

Signed-off-by: Kunwu Chan <chentao@kylinos.cn>
Change-Id: I3c543f0f18fa397f8e9194d0c6260d78b157f3f7
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/123518
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>
Tested-by: k2ci <kernel-bot@kylinos.cn>
Code-Style: k2ci <kernel-bot@kylinos.cn>