KVM: selftests: Delete superfluous, unused "stage" variable in AMX test
Mainline: 46fee9e38995af9ae16a8cc7d05031486d44cf35
From: v6.8-rc5
Severity: Moderate

task: 200497

[ Upstream commit 46fee9e38995af9ae16a8cc7d05031486d44cf35 ]

Delete the AMX's tests "stage" counter, as the counter is no longer used,
which makes clang unhappy:

  x86_64/amx_test.c:224:6: error: variable 'stage' set but not used
          int stage, ret;
              ^
  1 error generated.

Note, "stage" was never really used, it just happened to be dumped out by
a (failed) assertion on run->exit_reason, i.e. the AMX test has no concept
of stages, the code was likely copy+pasted from a different test.

Fixes: c96f57b08012 ("KVM: selftests: Make vCPU exit reason test assertion common")
Reviewed-by: Jim Mattson <jmattson@google.com>
Link: https://lore.kernel.org/r/20240109220302.399296-1-seanjc@google.com
Signed-off-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 03aee9284d9b0ea12243815a0f054209f86f6adf)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ia55d74bed52a489ceb803a0e191f402de9616475
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/97825
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>