connector: Fix invalid conversion in cn_proc.h
Mainline: 06e785aeb9ea8a43d0a3967c1ba6e69d758e82d4
From: v6.10-rc2
Severity: Moderate

task: 334535

[ Upstream commit 06e785aeb9ea8a43d0a3967c1ba6e69d758e82d4 ]

The implicit conversion from unsigned int to enum
proc_cn_event is invalid, so explicitly cast it
for compilation in a C++ compiler.
/usr/include/linux/cn_proc.h: In function 'proc_cn_event valid_event(proc_cn_event)':
/usr/include/linux/cn_proc.h:72:17: error: invalid conversion from 'unsigned int' to 'proc_cn_event' [-fpermissive]
   72 |         ev_type &= PROC_EVENT_ALL;
      |                 ^
      |                 |
      |                 unsigned int

Signed-off-by: Matt Jan <zoo868e@gmail.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 9258d795978f398ecf2d222a8388cff81d37d34d)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I928501db57b4e26acb85d5d4fe82ff9a2216ad81
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/122670
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>