KYLIN: rtl8852CU: Fix UTF-8 decode error
Mainline: KYLIN-only
Severity: Low

task: 530899

In the tools/testing/selftests/dt execution make will appear the following error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position
4856: invalid start byte

To solve the above problems, delete the abnormal characters that affect the code

Fixes: 92d2fb91966f ("REALTEK: net: Add realtek rtl8852CU/rtl8832CU driver")
Change-Id: Ic3026425eaa8734e3fd9b9512486ec99d56195bf
Signed-off-by: Liu Hao <liuhao1@kylinos.cn>
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/117140
Code-Style: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 何敏红 <heminhong@kylinos.cn>
Tested-by: kernel-bot <kernel-bot@kylinos.cn>
Reviewed-by: 刘云 <liuyun01@kylinos.cn>