ASoC: ops: dynamically allocate struct snd_ctl_elem_value
Mainline: 7e10d7242ea8a5947878880b912ffa5806520705
From: v6.17-rc1
Severity: Moderate

task: 517535

[ Upstream commit 7e10d7242ea8a5947878880b912ffa5806520705 ]

This structure is really too larget to be allocated on the stack:

sound/soc/soc-ops.c:435:5: error: stack frame size (1296) exceeds limit (1280) in 'snd_soc_limit_volume' [-Werror,-Wframe-larger-than]

Change the function to dynamically allocate it instead.

There is probably a better way to do it since only two integer fields
inside of that structure are actually used, but this is the simplest
rework for the moment.

Fixes: 783db6851c18 ("ASoC: ops: Enforce platform maximum on initial value")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250610093057.2643233-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 4c39fc79ae2560c28cd1e73dd4a90170b0c7a78f)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Id22beccfbbb81c639cba825335c18961c9cffd81
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/100704
Reviewed-by: 刘云 <liuyun01@kylinos.cn>