KYLIN: resctrl: mpam: Switch platform_driver .remove to .remove_new
Mainline: KYLIN-only
Severity: Low

The mpam_msc_driver was still using the legacy .remove callback, which
expects an int-returning remove function. However, mpam_msc_drv_remove()
returns void, causing a -Werror=incompatible-pointer-types build failure.

Update the driver to use the new .remove_new field, which accepts a
void-returning remove callback.

This fixes the following build error:

  drivers/resctrl/mpam_devices.c:1923:19: error: initialization of
  ‘int (*)(struct platform_device *)’ from incompatible pointer type
  ‘void (*)(struct platform_device *)’

No functional change intended.

K2CI-Arch: All
Fixes: 8478532b9402 ("arm_mpam: Add probe/remove for mpam msc driver and kbuild boiler plate")
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: If32b5fc9a4a8bce0afc85d084efafb788e8a02c0
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/151083
Tested-by: kernel-bot <kernel-bot@kylinos.cn>