dma/contiguous: avoid warning about unused size_bytes
Mainline: d7b98ae5221007d3f202746903d4c21c7caf7ea9
From: v6.15-rc4
Severity: Moderate

task: 460826

[ Upstream commit d7b98ae5221007d3f202746903d4c21c7caf7ea9 ]

When building with W=1, this variable is unused for configs with
CONFIG_CMA_SIZE_SEL_PERCENTAGE=y:

kernel/dma/contiguous.c:67:26: error: 'size_bytes' defined but not used [-Werror=unused-const-variable=]

Change this to a macro to avoid the warning.

Fixes: c64be2bb1c6e ("drivers: add Contiguous Memory Allocator")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Marek Szyprowski <m.szyprowski@samsung.com>
Link: https://lore.kernel.org/r/20250409151557.3890443-1-arnd@kernel.org
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 92d55d7051833116af0fc8664599f458e3dfa858)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I5d2af4606ec8c8a8462fae34f801cc260b0a00bc
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/59831
Reviewed-by: 刘云 <liuyun01@kylinos.cn>